In [12]:
import pandas as pd

cols = ['대지위치', '법정동코드명', '주용도코드명', '기타용도내용',
        '사용승인일자', '대지면적', '세대수']

df_원본 = pd.read_csv('../data/서울시 건축물대장 표제부.csv',
                      encoding='cp949',
                      encoding_errors='ignore',
                      on_bad_lines='skip',
                      usecols=cols)

# 법정동별 건물 형태 비율
# 먼저 전체 데이터(필터링 전)에서 봐야 해
형태_분류 = df_원본['기타용도내용'].str.extract(
    r'(아파트|연립주택|다세대주택|단독주택|다가구)')

df_원본['건물형태'] = 형태_분류[0].fillna('기타')

pivot = df_원본.groupby(['법정동코드명', '건물형태']).size().unstack(fill_value=0)
pivot['총계'] = pivot.sum(axis=1)

# 비율로 변환
pivot_ratio = pivot.div(pivot['총계'], axis=0).round(3)
print(pivot_ratio.sort_values('다세대주택', ascending=False).head(20))

건물형태       기타    다가구  다세대주택   단독주택    아파트   연립주택   총계
법정동코드명
구산동     0.374  0.061  0.388  0.120  0.034  0.023  1.0
역촌동     0.340  0.118  0.385  0.122  0.025  0.010  1.0
행촌동     0.371  0.186  0.362  0.056  0.014  0.012  1.0
삼전동     0.468  0.157  0.340  0.026  0.002  0.008  1.0
응봉동     0.508  0.060  0.338  0.007  0.081  0.007  1.0
누상동     0.427  0.076  0.325  0.096  0.003  0.073  1.0
궁동      0.347  0.146  0.319  0.053  0.025  0.111  1.0
송파동     0.459  0.106  0.309  0.075  0.038  0.014  1.0
금호동1가   0.504  0.041  0.305  0.021  0.129  0.000  1.0
석촌동     0.512  0.112  0.303  0.052  0.008  0.013  1.0
신교동     0.548  0.065  0.302  0.060  0.010  0.015  1.0
당인동     0.369  0.277  0.291  0.035  0.000  0.028  1.0
원서동     0.589  0.026  0.290  0.086  0.000  0.009  1.0
화곡동     0.447  0.165  0.286  0.056  0.034  0.011  1.0
녹번동     0.395  0.164  0.285  0.101  0.038  0.018  1.0
방이동     0.493  0.068  0.280  0.055  0.075  0.030  1.0
망원동     0.393  0.224  0.271  0.063  0.030  0.019  1.0
갈현동     0.482  0.037  0.269  0.181  0.011  0.020  1.0
성산동     0.428  0.180  0.264  0.074  0.034  0.021  1.0
합정동     0.488  0.163  0.260  0.059  0.014  0.016  1.0

In [5]:
pivot_ratio['연립+다세대'] = pivot_ratio.get('연립주택', 0) + pivot_ratio.get('다세대주택', 0)
print(pivot_ratio['연립+다세대'].sort_values(ascending=True).to_string())

법정동코드명
흥인동       0.000
평동        0.000
돈의동       0.000
산림동       0.000
삼각동       0.000
팔판동       0.000
도원동       0.000
오장동       0.000
주자동       0.000
오쇠동       0.000
도렴동       0.000
청암동       0.000
오곡동       0.000
예지동       0.000
익선동       0.000
사간동       0.000
인사동       0.000
상왕십리동     0.000
인현동1가     0.000
당주동       0.000
현저동       0.000
인현동2가     0.000
예관동       0.000
서린동       0.000
서소문동      0.000
태평로2가     0.000
태평로1가     0.000
당동        0.000
세종로       0.000
다동        0.000
문래동2가     0.000
인의동       0.000
소공동       0.000
와룡동       0.000
용산동1가     0.000
무학동       0.000
문래동3가     0.000
무교동       0.000
묘동        0.000
문래동4가     0.000
문래동5가     0.000
문래동6가     0.000
을지로1가     0.000
을지로2가     0.000
을지로3가     0.000
명동2가      0.000
명동1가      0.000
을지로4가     0.000
문배동       0.000
북창동       0.000
미근동       0.000
필동1가      0.000
을지로5가     0.000
운니동       0.000
하중동       0.000
용산동5가     0.000
용산동3가     0.000
봉래동1가     0.000
을지로7가     0.000
동소문동5가    0.000
봉래동2가     0.000
봉익동       0.000
동소문동2가    0.000
의주로1가     0.000
의주로2가     0.000
방산동       0.000
송월동       0.000
입정동       0.000
송현동       0.000
정동        0.000
회현동3가     0.000
교북동       0.000
교남동       0.000
신천동       0.000
광희동1가     0.000
관훈동       0.000
관철동       0.000
관수동       0.000
과해동       0.000
충무로3가     0.000
공평동       0.000
종로1가      0.000
충무로2가     0.000
중학동       0.000
종로2가      0.000
여의도동      0.000
경운동       0.000
견지동       0.000
종로4가      0.000
양화동       0.000
충무로1가     0.000
효제동       0.000
강일동       0.000
훈정동       0.000
종로5가      0.000
압구정동      0.000
초동        0.000
양평동       0.000
주교동       0.000
종로3가      0.000
충무로4가     0.000
청진동       0.000
남대문로3가    0.000
장사동       0.000
순화동       0.000
남산동3가     0.000
남산동2가     0.000
남산동1가     0.000
남대문로5가    0.000
남대문로4가    0.000
수하동       0.000
충무로5가     0.000
남대문로2가    0.000
장교동       0.000
남대문로1가    0.000
장지동       0.000
수표동       0.000
낙원동       0.000
충정로1가     0.000
내자동       0.000
재동        0.000
수송동       0.000
저동1가      0.000
신문로1가     0.000
저동2가      0.000
적선동       0.000
권농동       0.000
궁정동       0.000
수서동       0.000
남창동       0.000
남학동       0.000
영등포동4가    0.003
동선동1가     0.003
쌍림동       0.003
원남동       0.004
충신동       0.004
연지동       0.004
보문동1가     0.005
을지로6가     0.005
당산동5가     0.005
묵정동       0.005
보문동3가     0.008
율현동       0.008
남영동       0.008
내곡동       0.008
화동        0.008
진관동       0.008
종로6가      0.008
영등포동3가    0.009
영등포동8가    0.009
소격동       0.009
자곡동       0.009
문래동1가     0.009
통의동       0.010
광희동2가     0.010
삼청동       0.010
개화동       0.010
당산동2가     0.012
원지동       0.012
안국동       0.012
신설동       0.013
계동        0.014
누하동       0.015
신원동       0.015
대현동       0.015
양평동1가     0.015
양평동3가     0.015
영등포동5가    0.016
통인동       0.017
봉원동       0.017
동소문동3가    0.017
합동        0.017
당산동3가     0.018
신계동       0.018
당산동       0.018
내수동       0.019
황학동       0.020
이화동       0.021
한강로2가     0.021
회현동2가     0.021
길음동       0.022
당산동1가     0.022
회현동1가     0.023
냉천동       0.023
안암동5가     0.023
충정로2가     0.023
필동2가      0.024
영천동       0.024
한강로3가     0.024
만리동2가     0.025
예장동       0.025
하왕십리동     0.025
본동        0.025
산천동       0.025
보문동4가     0.026
공덕동       0.026
홍익동       0.026
염곡동       0.027
명륜4가      0.028
가회동       0.028
영등포동2가    0.029
보문동7가     0.029
당산동4가     0.030
영등포동1가    0.030
답십리동      0.031
도선동       0.031
신문로2가     0.031
영등포동      0.031
영등포동7가    0.032
체부동       0.032
중림동       0.033
안암동1가     0.033
삼선동2가     0.034
원효로2가     0.034
마장동       0.034
하월곡동      0.036
창성동       0.036
청량리동      0.036
용두동       0.037
필동3가      0.037
천왕동       0.037
세곡동       0.038
송정동       0.038
영등포동6가    0.039
삼선동1가     0.039
마곡동       0.039
양평동2가     0.039
효자동       0.039
잠원동       0.040
도곡동       0.040
제기동       0.040
무악동       0.040
회기동       0.041
보문동5가     0.041
안암동2가     0.042
이문동       0.042
상암동       0.043
상월곡동      0.043
한강로1가     0.043
신촌동       0.045
성수동2가     0.046
동자동       0.047
흑석동       0.047
신내동       0.047
동선동4가     0.048
필운동       0.048
신공덕동      0.049
이촌동       0.049
노량진동      0.049
신길동       0.050
우면동       0.051
동교동       0.051
전농동       0.054
도화동       0.055
용답동       0.055
동선동2가     0.055
성수동1가     0.055
망우동       0.055
원효로3가     0.056
만리동1가     0.056
신도림동      0.056
도림동       0.057
돈암동       0.057
충정로3가     0.057
대흥동       0.058
행당동       0.059
옥천동       0.060
옥수동       0.060
서초동       0.061
가양동       0.061
삼성동       0.064
능동        0.064
보광동       0.065
금호동4가     0.066
동소문동1가    0.066
화양동       0.068
대림동       0.069
명륜2가      0.070
북아현동      0.071
갈월동       0.071
사근동       0.071
보문동6가     0.072
중계동       0.072
양평동4가     0.072
이태원동      0.072
노고산동      0.073
원효로1가     0.073
면목동       0.074
군자동       0.074
신림동       0.074
창신동       0.075
상봉동       0.075
신당동       0.076
삼선동4가     0.078
풍납동       0.079
논현동       0.079
동소문동7가    0.079
안암동3가     0.080
성북동       0.080
양평동5가     0.081
휘경동       0.083
서빙고동      0.084
석관동       0.085
창천동       0.085
남현동       0.085
번동        0.085
장충동1가     0.086
중화동       0.086
명륜3가      0.086
염창동       0.088
동소문동6가    0.089
남가좌동      0.089
공항동       0.089
광장동       0.090
홍지동       0.091
혜화동       0.091
청파동3가     0.091
일원동       0.092
항동        0.092
숭인동       0.092
보문동2가     0.093
청담동       0.093
천연동       0.094
종암동       0.094
미아동       0.095
양재동       0.097
원효로4가     0.098
고덕동       0.098
삼선동5가     0.098
수색동       0.098
가산동       0.099
옥인동       0.099
홍제동       0.100
반포동       0.100
평창동       0.101
대신동       0.102
염리동       0.102
묵동        0.103
금호동2가     0.104
사직동       0.104
장충동2가     0.104
대치동       0.104
동선동3가     0.105
부암동       0.107
신대방동      0.107
연희동       0.107
자양동       0.107
거여동       0.108
안암동4가     0.110
구로동       0.110
방화동       0.110
고척동       0.110
봉천동       0.111
외발산동      0.112
청운동       0.114
도봉동       0.114
신수동       0.115
청파동2가     0.115
당산동6가     0.115
하계동       0.115
중곡동       0.117
서계동       0.118
창전동       0.118
성북동1가     0.119
신창동       0.119
장안동       0.120
방학동       0.122
신정동       0.125
수유동       0.126
독산동       0.128
명일동       0.131
토정동       0.133
공릉동       0.133
마천동       0.133
상계동       0.134
한남동       0.134
월계동       0.135
서교동       0.136
동선동5가     0.136
상일동       0.137
상수동       0.139
장위동       0.139
시흥동       0.140
역삼동       0.140
가리봉동      0.142
천호동       0.145
현석동       0.147
금호동3가     0.148
마포동       0.151
후암동       0.153
방배동       0.153
구수동       0.155
창동        0.155
정릉동       0.156
동빙고동      0.158
쌍문동       0.159
명륜1가      0.163
둔촌동       0.163
동소문동4가    0.165
등촌동       0.166
용강동       0.167
용문동       0.169
홍은동       0.170
홍파동       0.170
연남동       0.171
대방동       0.172
잠실동       0.172
용산동2가     0.173
가락동       0.180
구의동       0.183
사당동       0.183
오류동       0.184
증산동       0.185
효창동       0.191
신사동       0.191
상도1동      0.197
아현동       0.198
삼선동3가     0.204
길동        0.205
성내동       0.207
청파동1가     0.208
동숭동       0.210
내발산동      0.210
상도동       0.211
암사동       0.211
문정동       0.212
구기동       0.213
개포동       0.217
우이동       0.217
동작동       0.219
양평동6가     0.221
연건동       0.223
신영동       0.225
주성동       0.230
응암동       0.234
대조동       0.243
북가좌동      0.249
중동        0.252
개봉동       0.255
목동        0.255
불광동       0.267
신월동       0.275
합정동       0.276
오금동       0.277
성산동       0.285
갈현동       0.289
망원동       0.290
화곡동       0.297
원서동       0.299
녹번동       0.303
금호동1가     0.305
방이동       0.310
석촌동       0.316
온수동       0.316
신교동       0.317
당인동       0.319
송파동       0.323
응봉동       0.345
삼전동       0.348
행촌동       0.374
역촌동       0.395
누상동       0.398
구산동       0.411
궁동        0.430
용산동6가     0.516
용산동4가     0.909

In [9]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [ ]:
df_원본['기타용도내용'].value_counts().sort_values(ascending=False)

In [21]:
import pandas as pd

cols = ['대지위치', '법정동코드명', '주용도코드명', '기타용도내용',
        '사용승인일자', '대지면적', '세대수']

df_원본 = pd.read_csv('../data/서울시 건축물대장 표제부.csv',
                      encoding='cp949',
                      encoding_errors='ignore',
                      on_bad_lines='skip',
                      usecols=cols)

# 법정동별 건물 형태 비율
# 먼저 전체 데이터(필터링 전)에서 봐야 해
형태_분류 = df_원본['기타용도내용'].str.extract(
    r'(아파트|연립주택|다세대주택|단독주택|다가구|도시형생활주택|오피스텔)'
)

df_원본['건물형태'] = 형태_분류[0].replace({
    '도시형생활주택': '다세대주택'
}).fillna('기타')

pivot = df_원본.groupby(['법정동코드명', '건물형태']).size().unstack(fill_value=0)
pivot['총계'] = pivot.sum(axis=1)


# 비율로 변환
pivot_ratio = pivot.div(pivot['총계'], axis=0).round(3)
print(pivot_ratio.sort_values('다세대주택', ascending=False).head(20))

건물형태       기타    다가구  다세대주택   단독주택    아파트   연립주택   오피스텔   총계
법정동코드명
구산동     0.370  0.061  0.392  0.120  0.034  0.023  0.000  1.0
역촌동     0.336  0.118  0.385  0.121  0.025  0.010  0.004  1.0
궁동      0.300  0.146  0.372  0.053  0.024  0.106  0.000  1.0
삼전동     0.436  0.157  0.370  0.026  0.002  0.008  0.002  1.0
행촌동     0.371  0.186  0.362  0.056  0.014  0.012  0.000  1.0
화곡동     0.382  0.165  0.342  0.055  0.032  0.011  0.012  1.0
응봉동     0.506  0.060  0.340  0.007  0.081  0.007  0.000  1.0
송파동     0.425  0.106  0.339  0.074  0.038  0.014  0.004  1.0
석촌동     0.486  0.112  0.329  0.052  0.008  0.013  0.000  1.0
누상동     0.427  0.076  0.325  0.096  0.003  0.073  0.000  1.0
방이동     0.447  0.068  0.314  0.055  0.074  0.029  0.013  1.0
오금동     0.462  0.077  0.312  0.069  0.052  0.025  0.002  1.0
금호동1가   0.504  0.041  0.305  0.021  0.129  0.000  0.000  1.0
신교동     0.548  0.065  0.302  0.060  0.010  0.015  0.000  1.0
당인동     0.369  0.277  0.291  0.035  0.000  0.028  0.000  1.0
원서동     0.589  0.026  0.290  0.086  0.000  0.009  0.000  1.0
녹번동     0.392  0.164  0.284  0.101  0.037  0.018  0.005  1.0
양평동6가   0.497  0.085  0.277  0.017  0.028  0.023  0.073  1.0
망원동     0.391  0.224  0.273  0.063  0.030  0.019  0.000  1.0
갈현동     0.479  0.037  0.271  0.181  0.011  0.020  0.001  1.0

In [15]:
기타_mask = df_원본['건물형태'] == '기타'
print(df_원본[기타_mask]['기타용도내용'].value_counts().head(30))

기타용도내용
주택                112882
근린생활시설             33681
근린생활시설, 주택         18077
공동주택               17848
제2종근린생활시설          11446
주택, 근린생활시설          6100
점포                  3942
제1종근린생활시설           3632
주택, 점포              3415
주거시설                3291
교육연구시설              3218
경비실                 2844
근린생활시설,주택           2382
근린생활시설및주택           2123
근린생활시설              1748
영업용                 1746
근린생활시설 및 주택         1704
업무시설                1645
제1,2종근린생활시설         1602
주거시설                1583
영업                  1581
지하주차장               1290
다중주택                1242
공장                  1105
교육연구및복지시설           1085
주택,근린생활시설           1056
제2종근린생활시설(사무소)      1027
창고                  1024
공동주택(다세대)            983
종교시설                 830
Name: count, dtype: int64

In [17]:
df_원본['주용도코드명'].value_counts().sort_values(ascending=False)

주용도코드명
단독주택          290155
공동주택          141801
제2종근린생활시설      63319
제1종근린생활시설      57877
업무시설           10288
교육연구시설          8256
노유자시설           3250
종교시설            2954
공장              2356
숙박시설            1988
자동차관련시설         1888
창고시설            1583
문화및집회시설         1421
판매시설            1225
근린생활시설           959
의료시설             799
위험물저장및처리시설       668
운동시설             355
교정및군사시설          290
운수시설             268
관광휴게시설           182
교육연구및복지시설        170
동물및식물관련시설        170
위락시설             167
분뇨.쓰레기처리시설       142
방송통신시설            94
국방,군사시설           93
자원순환관련시설          77
수련시설              73
묘지관련시설            47
판매및영업시설           41
발전시설              23
공공용시설             12
야영장시설             10
장례시설               6
다가구주택              2
가설건축물              1
교정시설               1
Name: count, dtype: int64

In [23]:
mask = df_원본['주용도코드명'] == '공동주택'
print(df_원본[mask]['기타용도내용'].value_counts().head(40))

기타용도내용
다세대주택                    32560
공동주택                     17757
아파트                       9854
공동주택(아파트)                 9420
공동주택(다세대주택)               8469
연립주택                      5416
경비실                       2754
도시형생활주택(단지형다세대)           2371
다세대주택(8세대)                1742
주거시설                      1457
지하주차장                     1198
도시형생활주택(단지형다세대주택)         1189
공동주택,다세대주택                1188
공동주택(다세대)                  983
다세대주택, 근린생활시설              915
다세대주택(9세대)                 873
도시형생활주택                    870
다세대주택(도시형생활주택/단지형다세대)      825
다세대주택(10세대)                738
다세대주택(6세대)                 713
주택                         659
공동주택(도시형생활주택)              600
다세대주택(7세대)                 582
다세대주택 및 근린생활시설             473
다세대주택,근린생활시설               456
다세대주택(4세대)                 411
경로당                        398
공동주택(연립주택)                 374
다세대주택(도시형생활주택)             370
다세대주택(5세대)                 334
주민공동시설                     333
다세대주택(3세대)                 331
공동주택(도시형생활주택-단지형다세대)       316
공동주택, 근린생활시설               315
단지형다세대주택                   313
협동주택                       298
공동주택(다세대주택),근린생활시설         283
다세대주택,제2종근린생활시설            282
근린생활시설 및 다세대주택             282
공동주택외1                     269
Name: count, dtype: int64

In [24]:
아파트_키워드 = ['아파트', '경비실', '지하주차장', '경로당', '주민공동시설', '관리사무소']

mask = (
    (df_원본['주용도코드명'] == '공동주택') &
    ~df_원본['기타용도내용'].str.contains('|'.join(아파트_키워드), na=False)
)

df_filtered = df_원본[mask]
print(df_filtered.shape)
print(df_filtered['기타용도내용'].value_counts().head(20))

(112901, 8)
기타용도내용
다세대주택                    32560
공동주택                     17757
공동주택(다세대주택)               8469
연립주택                      5416
도시형생활주택(단지형다세대)           2371
다세대주택(8세대)                1742
주거시설                      1457
도시형생활주택(단지형다세대주택)         1189
공동주택,다세대주택                1188
공동주택(다세대)                  983
다세대주택, 근린생활시설              915
다세대주택(9세대)                 873
도시형생활주택                    870
다세대주택(도시형생활주택/단지형다세대)      825
다세대주택(10세대)                738
다세대주택(6세대)                 713
주택                         659
공동주택(도시형생활주택)              600
다세대주택(7세대)                 582
다세대주택 및 근린생활시설             473
Name: count, dtype: int64

# 카카오 지도 매핑

In [41]:
import pandas as pd
cols = ['대지위치', '법정동코드명', '주용도코드명', '기타용도내용',
        '사용승인일자', '대지면적', '세대수', '주지번', '부지번']

df_원본 = pd.read_csv('../data/서울시 건축물대장 표제부.csv',
                      encoding='cp949',
                      encoding_errors='ignore',
                      on_bad_lines='skip',
                      usecols=cols)

In [42]:
아파트_키워드 = ['아파트', '경비실', '지하주차장', '경로당', '주민공동시설', '관리사무소']

mask = (
    (df_원본['주용도코드명'] == '공동주택') &
    ~df_원본['기타용도내용'].str.contains('|'.join(아파트_키워드), na=False)
)

df = df_원본[mask].copy()

# 건축연도 추출 및 2022 이하 필터
df['건축연도'] = pd.to_numeric(
    df['사용승인일자'].astype(str).str[:4], errors='coerce')
df = df[df['건축연도'].notna() & (df['건축연도'] <= 2022)].copy()

print(f'최종 건물 수: {len(df):,}')

최종 건물 수: 110,359

In [43]:
'''
idx        # df의 원본 인덱스
lng        # 경도
lat        # 위도
hdong_code # 행정동 코드 (10자리, 예: 1150063000)
hdong_name # 행정동명 (예: 방화1동)
'''
import requests
import time
import os
import pandas as pd
from dotenv import load_dotenv

load_dotenv()
KAKAO_KEY = os.getenv('REST_API')
CHECKPOINT = '../data/checkpoint.csv'

def geocode(address):
    url = "https://dapi.kakao.com/v2/local/search/address.json"
    headers = {"Authorization": f"KakaoAK {KAKAO_KEY}"}
    params = {"query": address}
    try:
        res = requests.get(url, headers=headers, params=params, timeout=5)
        docs = res.json().get('documents', [])
        if docs:
            addr = docs[0].get('address', {})
            return {
                'lng': float(docs[0]['x']),
                'lat': float(docs[0]['y']),
                'hdong_code': addr.get('h_code'),
                'hdong_name': addr.get('region_3depth_h_name'),
                'b_code': addr.get('b_code')
            }
        return {'lng': None, 'lat': None, 'hdong_code': None, 'hdong_name': None, 'b_code': None}
    except:
        return {'lng': None, 'lat': None, 'hdong_code': None, 'hdong_name': None, 'b_code': None}

# 체크포인트 초기화
if os.path.exists(CHECKPOINT):
    os.remove(CHECKPOINT)

df_done = pd.DataFrame(columns=['idx', 'lng', 'lat', 'hdong_code', 'hdong_name', 'b_code'])
results = []
total = len(df)

for i, (idx, row) in enumerate(df.iterrows()):
    result = geocode(row['대지위치'])
    result['idx'] = idx
    results.append(result)

    if len(results) % 1000 == 0:
        df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)
        df_done.to_csv(CHECKPOINT, index=False, encoding='utf-8-sig')
        results = []
        print(f'{len(df_done):,} / {total:,} 완료')

    time.sleep(0.05)

if results:
    df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)
    df_done.to_csv(CHECKPOINT, index=False, encoding='utf-8-sig')

print(f'완료. 총 {len(df_done):,}건')

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

1,000 / 110,359 완료
2,000 / 110,359 완료
3,000 / 110,359 완료
4,000 / 110,359 완료
5,000 / 110,359 완료
6,000 / 110,359 완료
7,000 / 110,359 완료
8,000 / 110,359 완료
9,000 / 110,359 완료
10,000 / 110,359 완료
11,000 / 110,359 완료
12,000 / 110,359 완료
13,000 / 110,359 완료
14,000 / 110,359 완료
15,000 / 110,359 완료
16,000 / 110,359 완료
17,000 / 110,359 완료
18,000 / 110,359 완료
19,000 / 110,359 완료
20,000 / 110,359 완료
21,000 / 110,359 완료
22,000 / 110,359 완료
23,000 / 110,359 완료
24,000 / 110,359 완료
25,000 / 110,359 완료
26,000 / 110,359 완료
27,000 / 110,359 완료
28,000 / 110,359 완료
29,000 / 110,359 완료
30,000 / 110,359 완료
31,000 / 110,359 완료
32,000 / 110,359 완료
33,000 / 110,359 완료
34,000 / 110,359 완료
35,000 / 110,359 완료
36,000 / 110,359 완료
37,000 / 110,359 완료
38,000 / 110,359 완료
39,000 / 110,359 완료
40,000 / 110,359 완료
41,000 / 110,359 완료
42,000 / 110,359 완료
43,000 / 110,359 완료
44,000 / 110,359 완료
45,000 / 110,359 완료
46,000 / 110,359 완료
47,000 / 110,359 완료
48,000 / 110,359 완료
49,000 / 110,359 완료
50,000 / 110,359 완료
51,000 / 110,359 완료
52,000 / 110,359 완료
53,000 / 110,359 완료
54,000 / 110,359 완료
55,000 / 110,359 완료
56,000 / 110,359 완료
57,000 / 110,359 완료
58,000 / 110,359 완료
59,000 / 110,359 완료
60,000 / 110,359 완료
61,000 / 110,359 완료
62,000 / 110,359 완료
63,000 / 110,359 완료
64,000 / 110,359 완료
65,000 / 110,359 완료
66,000 / 110,359 완료
67,000 / 110,359 완료
68,000 / 110,359 완료
69,000 / 110,359 완료
70,000 / 110,359 완료
71,000 / 110,359 완료
72,000 / 110,359 완료
73,000 / 110,359 완료
74,000 / 110,359 완료
75,000 / 110,359 완료
76,000 / 110,359 완료
77,000 / 110,359 완료
78,000 / 110,359 완료
79,000 / 110,359 완료
80,000 / 110,359 완료
81,000 / 110,359 완료
82,000 / 110,359 완료
83,000 / 110,359 완료
84,000 / 110,359 완료
85,000 / 110,359 완료
86,000 / 110,359 완료
87,000 / 110,359 완료
88,000 / 110,359 완료
89,000 / 110,359 완료
90,000 / 110,359 완료
91,000 / 110,359 완료
92,000 / 110,359 완료
93,000 / 110,359 완료
94,000 / 110,359 완료
95,000 / 110,359 완료
96,000 / 110,359 완료
97,000 / 110,359 완료
98,000 / 110,359 완료
99,000 / 110,359 완료
100,000 / 110,359 완료
101,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

102,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

103,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

104,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

105,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

106,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

107,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

108,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

109,000 / 110,359 완료

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:52: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

110,000 / 110,359 완료
완료. 총 110,359건

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/1976395888.py:60: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_done = pd.concat([df_done, pd.DataFrame(results)], ignore_index=True)

In [114]:
df_geo = pd.read_csv('../data/checkpoint.csv')
print(len(df_geo))
print(df_geo['hdong_code'].isna().sum())  # 매핑 실패 건수

110359
10638

In [70]:
df_geo.head()

   idx         lng        lat hdong_code hdong_name        b_code
0    1  126.961305  37.552684    1144056        공덕동  1.144010e+09
1   15  126.900435  37.524457    1156055       당산1동  1.156011e+09
2   31  126.858754  37.520246    1147062       신정1동  1.147010e+09
3   32  126.838704  37.526693    1147056       신월1동  1.147010e+09
4   33  126.867719  37.541744    1147053        목3동  1.147010e+09

In [112]:
import pandas as pd

# 1. 체크포인트 로드
df_geo = pd.read_csv('../data/checkpoint.csv')

# 2. hdong_code 7자리 변환
df_geo['hdong_code'] = df_geo['hdong_code'].astype(str).str[:7]

# 3. 행정동명 후처리
dong_rename = {
    '상일1동': '상일동',
    '상일2동': '강일동'
}
df_geo['hdong_name'] = df_geo['hdong_name'].replace(dong_rename)

# 4. 행정동별 건물 수 파악
dong_count = df_geo.groupby(['hdong_code', 'hdong_name']).size().reset_index(name='건물수')
dong_count = dong_count.sort_values('건물수', ascending=False)

print(f'총 행정동 수: {len(dong_count)}')
print(f'좌표 없음(매핑 실패): {df_geo["hdong_code"].isna().sum():,}건')
print()
print(dong_count.to_string())

총 행정동 수: 423
좌표 없음(매핑 실패): 0건

    hdong_code   hdong_name   건물수
186    1138062          역촌동  1179
249    1150059         화곡본동  1080
392    1171061          삼전동  1079
391    1171060          석촌동  1058
243    1150054         화곡1동  1041
205    1141072        북가좌2동   814
142    1130566          인수동   796
389    1171058         송파1동   773
248    1150059         화곡8동   759
181    1138056          구산동   747
400    1171065         잠실본동   741
223    1147052          목2동   739
180    1138055         갈현2동   711
178    1138053         불광2동   708
237    1147065         신정4동   708
176    1138051          녹번동   674
386    1171056         방이2동   662
308    1159056         상도4동   640
196    1141061          연희동   635
201    1141068         홍은2동   630
177    1138052         불광1동   629
69     1121577         중곡4동   622
233    1147061         신월7동   613
412    1174057         암사1동   611
187    1138063         신사1동   602
367    1168064         역삼1동   578
388    1171057          오금동   575
185    1138060         응암3동   566
179    1138055         갈현1동   551
141    1130564          우이동   544
182    1138057          대조동   539
307    1159055         상도3동   536
77     1121586         구의2동   536
219    1144072         성산1동   532
246    1150057         화곡4동   519
273    1153079          수궁동   517
355    1165065         양재2동   513
326    1162062          인헌동   512
97     1126056         면목본동   510
338    1162077          난곡동   507
148    1132052         도봉1동   501
416    1174061         천호2동   498
144    1132051          창2동   492
421    1174068           길동   492
138    1130561         수유1동   491
150    1132066         쌍문1동   491
215    1144068          합정동   488
244    1150055         화곡2동   487
155    1132070         방학2동   483
216    1144069         망원1동   481
132    1130554          송중동   481
136    1130560          번2동   478
305    1159053         상도1동   475
34     1117055          청파동   470
126    1129076         장위1동   469
354    1165065         양재1동   467
225    1147054          목4동   451
415    1174060         천호1동   444
353    1165062         방배4동   443
118    1129063         정릉2동   442
341    1165053         서초3동   437
214    1144066          서교동   435
224    1147053          목3동   435
358    1168052         논현1동   431
270    1153076         개봉3동   430
130    1130553          미아동   424
324    1162060          은천동   423
247    1150059         화곡6동   421
183    1138058         응암1동   415
337    1162076          미성동   415
44     1117068          한남동   415
76     1121585         구의1동   413
395    1171063         가락2동   411
268    1153074         개봉1동   403
420    1174066         성내3동   400
269    1153075         개봉2동   392
310    1159062         사당1동   388
131    1130553          삼양동   387
160    1135059         공릉1동   384
328    1162064          서원동   383
73     1121583         자양2동   380
207    1144056          공덕동   378
140    1130563         수유3동   377
278    1154563         독산3동   375
104    1126062          묵1동   374
366    1168063         대치4동   372
396    1171064         문정1동   369
31     1117051          후암동   368
4      1111056          평창동   366
72     1121582         자양1동   364
67     1121575         중곡2동   361
217    1144070         망원2동   361
86     1123065         장안1동   359
218    1144071          연남동   359
24     1114062          다산동   358
139    1130562         수유2동   357
129    1129081          석관동   356
227    1147056         신월1동   355
318    1162052         보라매동   355
350    1165060         방배1동   352
374    1168069         개포4동   348
280    1154567         시흥1동   347
133    1130555          송천동   347
283    1154570         시흥4동   345
254    1150061         우장산동   344
359    1168053         논현2동   343
120    1129065         정릉4동   338
11     1111065          혜화동   334
315    1159066          대방동   332
384    1171055         마천2동   331
241    1150053         등촌2동   329
393    1171062         가락본동   328
0      1111051        청운효자동   326
277    1154562         독산2동   325
188    1138063         신사2동   325
348    1165058         반포4동   320
255    1150062          공항동   320
151    1132067         쌍문2동   316
418    1174064         성내1동   316
256    1150063         방화1동   313
327    1162063          남현동   308
272    1153078         오류2동   308
383    1171054         마천1동   306
103    1126061         중화2동   304
419    1174065         성내2동   304
363    1168059         삼성2동   303
351    1165061         방배2동   302
220    1144073         성산2동   298
106    1126065         망우본동   298
323    1162059          청룡동   294
228    1147057         신월2동   293
32     1117052        용산2가동   293
110    1129052          성북동   292
399    1171064          장지동   290
94     1126052         면목2동   289
154    1132069         방학1동   289
313    1159065         사당4동   288
123    1129070          종암동   286
197    1141062         홍제1동   280
231    1147060         신월5동   279
203    1141070        남가좌2동   277
253    1150061         발산1동   276
385    1171056         방이1동   275
245    1150056         화곡3동   271
282    1154569         시흥3동   269
422    1174070         둔촌2동   269
263    1153055         구로4동   268
87     1123066         장안2동   267
102    1126060         중화1동   266
157    1135056         월계1동   264
78     1121587         구의3동   259
284    1154571         시흥5동   259
101    1126059         상봉2동   258
321    1162057          행운동   257
152    1132068         쌍문3동   256
349    1165059         방배본동   254
257    1150064         방화2동   254
81     1123054          제기동   254
267    1153073         고척2동   251
98     1126057       면목3.8동   250
345    1165056         반포1동   250
213    1144065          서강동   249
68     1121576         중곡3동   248
66     1121574         중곡1동   248
279    1154564         독산4동   245
194    1141056          충현동   244
370    1168065         역삼2동   244
230    1147059         신월4동   242
119    1129064         정릉3동   241
312    1159064         사당3동   239
170    1135066       상계3.4동   239
261    1153053         구로2동   238
107    1126066         망우3동   236
105    1126063          묵2동   236
6      1111058          교남동   235
330    1162066          서림동   232
229    1147058         신월3동   232
262    1153054         구로3동   231
377    1168073         일원1동   231
189    1138064          증산동   230
168    1135063         상계1동   227
127    1129077         장위2동   227
361    1168056          청담동   223
285    1156051        영등포본동   222
10     1111064          이화동   222
65     1121573          군자동   220
55     1120061      금호2.3가동   218
100    1126058         상봉1동   218
302    1156072         대림3동   217
145    1132051          창3동   217
3      1111055          부암동   216
320    1162056          성현동   216
271    1153077         오류1동   214
276    1154561         독산1동   213
171    1135067         상계5동   212
195    1141058          신촌동   212
198    1141064         홍제3동   212
331    1162068          신사동   209
99     1126057         면목7동   206
306    1159054         상도2동   205
82     1123056         전농1동   204
135    1130559          번1동   204
236    1147064         신정3동   203
53     1120058          응봉동   202
329    1162065          신원동   201
309    1159060          흑석동   200
339    1165051         서초1동   198
390    1171059         송파2동   196
13     1111068         창신2동   195
362    1168058         삼성1동   192
147    1132051          창5동   190
45     1117069         서빙고동   189
265    1153059         가리봉동   188
95     1126054         면목4동   188
275    1154551          가산동   185
417    1174062         천호3동   183
37     1117058          효창동   182
365    1168061         대치2동   181
317    1159068        신대방2동   180
293    1156062         양평2동   179
111    1129055          삼선동   175
91     1123073         휘경2동   175
75     1121584         자양4동   175
407    1174052          상일동   174
43     1117066        이태원2동   171
334    1162072          조원동   170
64     1121571          화양동   168
184    1138059         응암2동   167
381    1171053         거여1동   167
311    1159063         사당2동   166
96     1126055         면목5동   165
112    1129057          동선동   163
38     1117059          용문동   163
200    1141066         홍은1동   163
70     1121578           능동   162
161    1135060         공릉2동   162
108    1126068         신내1동   162
322    1162058         낙성대동   162
380    1171052         풍납2동   160
212    1144063          신수동   160
191    1138069          진관동   159
325    1162061          중앙동   158
352    1165062         방배3동   153
16     1111071         숭인2동   152
20     1114058          장충동   150
314    1159065         사당5동   149
162    1135061         중계본동   149
240    1150052         등촌1동   148
74     1121584         자양3동   147
239    1150051          염창동   146
46     1117070          보광동   145
360    1168054         압구정동   144
54     1120059        금호1가동   144
169    1135064         상계2동   143
290    1156058          도림동   142
266    1153072         고척1동   140
204    1141071        북가좌1동   138
80     1123053          용두동   136
294    1156063         신길1동   136
35     1117056        원효로1동   135
143    1132051          창1동   135
303    1159051        노량진1동   135
25     1114063          약수동   133
92     1123074         이문1동   132
398    1171064          위례동   132
368    1168065         도곡1동   132
332    1162069          신림동   129
71     1121581          광장동   128
211    1144061          염리동   127
124    1129071         월곡1동   126
210    1144060          대흥동   126
343    1165054          잠원동   124
333    1162071          난향동   124
411    1174056         고덕2동   124
116    1129061          보문동   123
134    1130557         삼각산동   120
408    1174053         명일1동   119
7      1111060          가회동   116
336    1162074          삼성동   116
36     1117057        원효로2동   112
289    1156056         당산2동   111
125    1129072         월곡2동   110
316    1159067        신대방1동   110
301    1156071         대림2동   109
357    1168051          신사동   108
376    1168072         일원본동   106
50     1120055          사근동   106
209    1144059          용강동   105
115    1129060          안암동   103
156    1132071         방학3동   101
258    1150064         방화3동   101
375    1168070          세곡동    99
163    1135061         하계1동    99
232    1147061         신월6동    98
335    1162073          대학동    98
58     1120065       성수1가1동    96
60     1120067       성수2가1동    96
382    1171053         거여2동    95
149    1132052         도봉2동    94
128    1129078         장위3동    93
49     1120054          마장동    92
264    1153056         구로5동    92
379    1171051         풍납1동    92
286    1156053         영등포동    92
300    1156070         대림1동    90
117    1129062         정릉1동    90
410    1174055         고덕1동    89
296    1156066         신길4동    88
88     1123070         청량리동    88
288    1156055         당산1동    88
153    1132068         쌍문4동    87
193    1141055         북아현동    86
85     1123061        답십리2동    86
364    1168060         대치1동    86
298    1156068         신길6동    85
42     1117065        이태원1동    84
340    1165052         서초2동    84
274    1153080           항동    83
413    1174058         암사2동    81
199    1141065         홍제2동    81
221    1144074          상암동    81
30     1114068          중림동    80
250    1150060         가양1동    80
79     1123051          신설동    80
190    1138065          수색동    79
372    1168067         개포2동    78
347    1165058         반포3동    76
84     1123060        답십리1동    75
1      1111053          사직동    74
208    1144058          도화동    72
369    1168065         도곡2동    71
90     1123072         휘경1동    70
304    1159052        노량진2동    69
192    1141052          천연동    69
414    1174059         암사3동    69
33     1117053          남영동    67
61     1120069       성수2가3동    67
297    1156067         신길5동    66
137    1130560          번3동    66
114    1129059         돈암2동    65
342    1165053         서초4동    64
281    1154568         시흥2동    62
41     1117064         이촌2동    62
93     1123075         이문2동    62
62     1120072          송정동    61
39     1117062         한강로동    61
158    1135057         월계2동    61
57     1120064          옥수동    61
89     1123071          회기동    61
59     1120066       성수1가2동    59
319    1162054          청림동    57
56     1120062        금호4가동    57
295    1156065         신길3동    57
122    1129068         길음2동    56
51     1120056         행당1동    56
235    1147063         신정2동    55
27     1114065         신당5동    55
146    1132051          창4동    53
259    1153051         신도림동    53
83     1123057         전농2동    53
394    1171063         가락1동    52
292    1156061         양평1동    51
63     1120079          용답동    50
23     1114061          신당동    49
378    1168075          수서동    48
121    1129066         길음1동    45
291    1156060          문래동    45
52     1120057         행당2동    44
26     1114064          청구동    42
48     1120053       왕십리도선동    42
47     1120052        왕십리2동    41
167    1135062         중계4동    41
222    1147051          목1동    40
19     1114057           필동    40
113    1129058         돈암1동    38
242    1150053         등촌3동    37
15     1111070         숭인1동    37
356    1165066          내곡동    36
409    1174054         명일2동    35
28     1114066          동화동    35
206    1144055          아현동    35
238    1147068         신정7동    34
373    1168067         개포3동    33
234    1147062         신정1동    30
29     1114067          황학동    30
299    1156069         신길7동    25
371    1168066         개포1동    25
406    1174052          강일동    24
165    1135062         중계1동    24
405    1174051          강일동    23
12     1111067         창신1동    23
5      1111057          무악동    23
346    1165057         반포2동    20
202    1141069        남가좌1동    20
40     1117063         이촌1동    19
21     1114059          광희동    18
159    1135058         월계3동    18
164    1135061         하계2동    17
9      1111063      종로5.6가동    16
166    1135062       중계2.3동    16
17     1114054          회현동    16
14     1111069         창신3동    16
175    1135072        상계10동    13
172    1135069       상계6.7동    13
2      1111054          삼청동    12
251    1150060         가양2동    10
260    1153052         구로1동     8
403    1171069         잠실4동     7
18     1114055           명동     7
109    1126069         신내2동     7
402    1171068         잠실3동     7
8      1111061  종로1.2.3.4가동     6
226    1147055          목5동     5
287    1156054          여의동     5
174    1135071         상계9동     4
401    1171067         잠실2동     3
173    1135070         상계8동     3
404    1171071         잠실6동     3
252    1150060         가양3동     2
22     1114060         을지로동     2
387    1171056          오륜동     1
344    1165055         반포본동     1
397    1171064         문정2동     1

In [58]:
df_c = pd.read_csv('crime_score.csv')
hd = df_c[['자치구','행정동','행정동코드']]
hd.rename(columns={'행정동코드': 'hdong_code'}, inplace=True)
hd['hdong_code'] = hd['hdong_code'].astype(str).str[:7]
hd.head()

/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/2504419008.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hd.rename(columns={'행정동코드': 'hdong_code'}, inplace=True)
/var/folders/ly/x0qvvd5d6_l1xs8p1h7k0zqw0000gn/T/ipykernel_73895/2504419008.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  hd['hdong_code'] = hd['hdong_code'].astype(str).str[:7]

   자치구  행정동 hdong_code
0  종로구  사직동    1101053
1  종로구  삼청동    1101054
2  종로구  부암동    1101055
3  종로구  평창동    1101056
4  종로구  무악동    1101057

In [60]:
hd2 = hd.merge(dong_count, left_on=['hdong_code'], right_on=['hdong_code'], how='left')
len(hd2)

425

In [113]:
# 5. 원본 df와 merge
df_final = df.join(df_geo.set_index('idx')[['lng', 'lat', 'hdong_code', 'hdong_name','b_code']])

df_final['b_code'] = df_final['b_code'].astype(str).str.split('.').str[0].str.zfill(10)
df_final['bun_padded'] = df_final['주지번'].astype(str).str.split('.').str[0].str.zfill(4)
df_final['ji_padded'] = df_final['부지번'].astype(str).str.split('.').str[0].str.zfill(4)
df_final['PNU'] = df_final['b_code'] + '0' + df_final['bun_padded'] + df_final['ji_padded']

print(df_final['PNU'].str.len().value_counts())
print(df_final['PNU'].isna().sum(), '건 PNU 생성 실패')

PNU
19    110359
Name: count, dtype: int64
0 건 PNU 생성 실패

In [74]:

# 6. 컬럼명 기존 HVI와 통일
df_final = df_final.rename(columns={
    '사용승인일자': 'SYDATE',
    '대지면적':    'total_area',
    '세대수':      'total_units'
})

# 7. 빅캠 반입용 저장
cols = ['대지위치', 'hdong_code', 'hdong_name',
        'SYDATE', 'total_area', 'total_units',
        'PNU', 'lng', 'lat']

df_final[cols].to_csv('../data/건축물대장_빅캠반입용.csv',
                      index=False, encoding='utf-8-sig')


print(f'\n반입용 데이터: {df_final[cols].shape}')
print(df_final[cols].isnull().sum())

반입용 데이터: (110359, 9)
대지위치               0
hdong_code         0
hdong_name     10638
SYDATE             0
total_area      6033
total_units     3055
PNU                0
lng            10638
lat            10638
dtype: int64

In [109]:
# 대지위치에서 구 이름 추출
# 예: '서울특별시 강서구 방화동 246-66' → '강서구'
df_final['gu_name'] = df_final['대지위치'].str.extract(r'서울특별시\s+(\S+구)')

print(df_final['gu_name'].value_counts())
print(df_final['gu_name'].isna().sum(), '건 추출 실패')

gu_name
은평구     8281
송파구     8114
강서구     6938
관악구     5326
강북구     5072
양천구     4812
광진구     4431
강남구     4376
마포구     4287
강동구     4255
동작구     4112
서초구     4094
중랑구     3967
서대문구    3861
성북구     3838
구로구     3816
도봉구     3705
용산구     2936
금천구     2625
종로구     2369
동대문구    2102
노원구     2089
영등포구    1808
성동구     1492
중구      1015
Name: count, dtype: int64
0 건 추출 실패

In [111]:
cols = ['대지위치', 'gu_name', 'hdong_code', 'hdong_name',
        'SYDATE', 'total_area', 'total_units',
        'PNU', 'lng', 'lat']

df_final[cols].to_csv('../data/건축물대장_빅캠반입용2.csv',
                      index=False, encoding='utf-8-sig')

print(f'저장 완료: {len(df_final[cols]):,}건')
print(df_final[cols].isnull().sum())

저장 완료: 99,721건
대지위치              0
gu_name           0
hdong_code        0
hdong_name        0
SYDATE            0
total_area     5401
total_units    2688
PNU               0
lng               0
lat               0
dtype: int64

In [31]:
df_원본.head()

                   대지위치 법정동코드명   대지면적     주용도코드명   기타용도내용   세대수      사용승인일자
0  서울특별시 강서구 방화동 246-66    방화동  274.0       단독주택  주택 및 창고   NaN  1989-06-30
1  서울특별시 마포구 아현동 751-11    아현동    0.0       공동주택     연립주택   6.0  1984-08-06
2   서울특별시 양천구 신월동 987-1    신월동    0.0       공동주택      아파트  96.0  1988-04-30
3   서울특별시 양천구 신정동 87-39    신정동    0.0  제1종근린생활시설   근린생활시설   0.0  1990-12-29
4  서울특별시 강서구 화곡동 102-29    화곡동  172.9       단독주택     단독주택   0.0  1990-08-18

In [75]:
# 노후도용: SYDATE 있는 것 (전체 다 있음)
# 집적도용: total_area > 0 이고 total_units 있는 것
# hdong_code 있는 것만 (행정동 매핑 성공)

df_valid = df_final[df_final['hdong_code'].notna()].copy()

print(f'행정동 매핑 성공: {len(df_valid):,}건 / 전체 {len(df_final):,}건')
print(f'매핑 실패: {df_final["hdong_code"].isna().sum():,}건\n')

# 노후도 기준 (SYDATE만 필요, 전체 유효)
old_count = df_valid.groupby(['hdong_code', 'hdong_name']).size().reset_index(name='노후도_건물수')

# 집적도 기준 (total_area > 0, total_units notna)
df_density = df_valid[(df_valid['total_area'] > 0) & df_valid['total_area'].notna() & df_valid['total_units'].notna()]
density_count = df_density.groupby(['hdong_code', 'hdong_name']).size().reset_index(name='집적도_건물수')

# 합쳐서 비교
dong_count = pd.merge(old_count, density_count, on=['hdong_code', 'hdong_name'], how='outer')
dong_count = dong_count.sort_values('노후도_건물수', ascending=False)

print(f'총 행정동 수: {len(dong_count)}')
print(dong_count.to_string())

행정동 매핑 성공: 110,359건 / 전체 110,359건
매핑 실패: 0건

총 행정동 수: 423
    hdong_code   hdong_name  노후도_건물수  집적도_건물수
186    1138062          역촌동     1179   1085.0
249    1150059         화곡본동     1080   1048.0
392    1171061          삼전동     1079   1032.0
391    1171060          석촌동     1058   1010.0
243    1150054         화곡1동     1041   1014.0
205    1141072        북가좌2동      814    703.0
142    1130566          인수동      796    585.0
389    1171058         송파1동      773    732.0
248    1150059         화곡8동      759    734.0
181    1138056          구산동      747    664.0
400    1171065         잠실본동      741    714.0
223    1147052          목2동      739    644.0
180    1138055         갈현2동      711    643.0
178    1138053         불광2동      708    585.0
237    1147065         신정4동      708    647.0
176    1138051          녹번동      674    567.0
386    1171056         방이2동      662    586.0
308    1159056         상도4동      640    558.0
196    1141061          연희동      635    426.0
201    1141068         홍은2동      630    442.0
177    1138052         불광1동      629    484.0
69     1121577         중곡4동      622    577.0
233    1147061         신월7동      613    146.0
412    1174057         암사1동      611    574.0
187    1138063         신사1동      602    519.0
367    1168064         역삼1동      578    527.0
388    1171057          오금동      575    402.0
185    1138060         응암3동      566    477.0
179    1138055         갈현1동      551    467.0
141    1130564          우이동      544    454.0
182    1138057          대조동      539    503.0
307    1159055         상도3동      536    485.0
77     1121586         구의2동      536    481.0
219    1144072         성산1동      532    406.0
246    1150057         화곡4동      519    508.0
273    1153079          수궁동      517    333.0
355    1165065         양재2동      513    485.0
326    1162062          인헌동      512    352.0
97     1126056         면목본동      510    440.0
338    1162077          난곡동      507    363.0
148    1132052         도봉1동      501    443.0
416    1174061         천호2동      498    436.0
144    1132051          창2동      492    447.0
421    1174068           길동      492    425.0
138    1130561         수유1동      491    415.0
150    1132066         쌍문1동      491    389.0
215    1144068          합정동      488    350.0
244    1150055         화곡2동      487    481.0
155    1132070         방학2동      483    414.0
216    1144069         망원1동      481    338.0
132    1130554          송중동      481    269.0
136    1130560          번2동      478    314.0
305    1159053         상도1동      475    371.0
34     1117055          청파동      470    419.0
126    1129076         장위1동      469    378.0
354    1165065         양재1동      467    283.0
225    1147054          목4동      451    388.0
415    1174060         천호1동      444    384.0
353    1165062         방배4동      443    388.0
118    1129063         정릉2동      442    339.0
341    1165053         서초3동      437    298.0
214    1144066          서교동      435    354.0
224    1147053          목3동      435    380.0
358    1168052         논현1동      431    365.0
270    1153076         개봉3동      430    354.0
130    1130553          미아동      424    320.0
324    1162060          은천동      423    278.0
247    1150059         화곡6동      421    400.0
183    1138058         응암1동      415    372.0
337    1162076          미성동      415    277.0
44     1117068          한남동      415    353.0
76     1121585         구의1동      413    362.0
395    1171063         가락2동      411    380.0
268    1153074         개봉1동      403    264.0
420    1174066         성내3동      400    372.0
269    1153075         개봉2동      392    354.0
310    1159062         사당1동      388    340.0
131    1130553          삼양동      387    338.0
160    1135059         공릉1동      384    268.0
328    1162064          서원동      383    212.0
73     1121583         자양2동      380    338.0
207    1144056          공덕동      378    146.0
140    1130563         수유3동      377    343.0
278    1154563         독산3동      375    341.0
104    1126062          묵1동      374    327.0
366    1168063         대치4동      372    339.0
396    1171064         문정1동      369    301.0
31     1117051          후암동      368    350.0
4      1111056          평창동      366    265.0
72     1121582         자양1동      364    322.0
67     1121575         중곡2동      361    341.0
217    1144070         망원2동      361    231.0
86     1123065         장안1동      359    198.0
218    1144071          연남동      359    307.0
24     1114062          다산동      358    308.0
139    1130562         수유2동      357    317.0
129    1129081          석관동      356    305.0
227    1147056         신월1동      355    266.0
318    1162052         보라매동      355    272.0
350    1165060         방배1동      352    300.0
374    1168069         개포4동      348    322.0
280    1154567         시흥1동      347    314.0
133    1130555          송천동      347    301.0
283    1154570         시흥4동      345    296.0
254    1150061         우장산동      344    324.0
359    1168053         논현2동      343    273.0
120    1129065         정릉4동      338    240.0
11     1111065          혜화동      334    256.0
315    1159066          대방동      332    292.0
384    1171055         마천2동      331    210.0
241    1150053         등촌2동      329    321.0
393    1171062         가락본동      328    297.0
0      1111051        청운효자동      326    305.0
277    1154562         독산2동      325    296.0
188    1138063         신사2동      325    264.0
348    1165058         반포4동      320    236.0
255    1150062          공항동      320    292.0
151    1132067         쌍문2동      316    287.0
418    1174064         성내1동      316    272.0
256    1150063         방화1동      313    268.0
327    1162063          남현동      308    245.0
272    1153078         오류2동      308    114.0
383    1171054         마천1동      306    190.0
103    1126061         중화2동      304    244.0
419    1174065         성내2동      304    253.0
363    1168059         삼성2동      303    266.0
351    1165061         방배2동      302    219.0
220    1144073         성산2동      298    168.0
106    1126065         망우본동      298    214.0
323    1162059          청룡동      294    147.0
228    1147057         신월2동      293    180.0
32     1117052        용산2가동      293    206.0
110    1129052          성북동      292    223.0
399    1171064          장지동      290    203.0
94     1126052         면목2동      289    208.0
154    1132069         방학1동      289    240.0
313    1159065         사당4동      288    244.0
123    1129070          종암동      286    224.0
197    1141062         홍제1동      280    177.0
231    1147060         신월5동      279    211.0
203    1141070        남가좌2동      277    201.0
253    1150061         발산1동      276    258.0
385    1171056         방이1동      275    234.0
245    1150056         화곡3동      271    267.0
282    1154569         시흥3동      269    161.0
422    1174070         둔촌2동      269    216.0
263    1153055         구로4동      268    245.0
87     1123066         장안2동      267    146.0
102    1126060         중화1동      266    204.0
157    1135056         월계1동      264    144.0
78     1121587         구의3동      259    229.0
284    1154571         시흥5동      259    211.0
101    1126059         상봉2동      258    235.0
321    1162057          행운동      257    179.0
152    1132068         쌍문3동      256    220.0
349    1165059         방배본동      254    213.0
257    1150064         방화2동      254    229.0
81     1123054          제기동      254    198.0
267    1153073         고척2동      251    163.0
98     1126057       면목3.8동      250    193.0
345    1165056         반포1동      250    195.0
213    1144065          서강동      249    146.0
68     1121576         중곡3동      248    224.0
66     1121574         중곡1동      248    220.0
279    1154564         독산4동      245    224.0
194    1141056          충현동      244    197.0
370    1168065         역삼2동      244    205.0
230    1147059         신월4동      242    169.0
119    1129064         정릉3동      241    154.0
312    1159064         사당3동      239    165.0
170    1135066       상계3.4동      239    165.0
261    1153053         구로2동      238    192.0
107    1126066         망우3동      236    215.0
105    1126063          묵2동      236    186.0
6      1111058          교남동      235    187.0
330    1162066          서림동      232    155.0
229    1147058         신월3동      232    127.0
262    1153054         구로3동      231    184.0
377    1168073         일원1동      231    160.0
189    1138064          증산동      230    173.0
168    1135063         상계1동      227    156.0
127    1129077         장위2동      227    181.0
361    1168056          청담동      223    157.0
285    1156051        영등포본동      222    170.0
10     1111064          이화동      222    203.0
65     1121573          군자동      220    195.0
55     1120061      금호2.3가동      218    186.0
100    1126058         상봉1동      218    165.0
302    1156072         대림3동      217    159.0
145    1132051          창3동      217    163.0
3      1111055          부암동      216    132.0
320    1162056          성현동      216    101.0
271    1153077         오류1동      214    162.0
276    1154561         독산1동      213    133.0
171    1135067         상계5동      212    130.0
195    1141058          신촌동      212    166.0
198    1141064         홍제3동      212    119.0
331    1162068          신사동      209    185.0
99     1126057         면목7동      206    170.0
306    1159054         상도2동      205    135.0
82     1123056         전농1동      204    177.0
135    1130559          번1동      204    180.0
236    1147064         신정3동      203    129.0
53     1120058          응봉동      202    185.0
329    1162065          신원동      201    116.0
309    1159060          흑석동      200    113.0
339    1165051         서초1동      198    125.0
390    1171059         송파2동      196    143.0
13     1111068         창신2동      195    182.0
362    1168058         삼성1동      192     90.0
147    1132051          창5동      190    148.0
45     1117069         서빙고동      189    121.0
265    1153059         가리봉동      188    131.0
95     1126054         면목4동      188    140.0
275    1154551          가산동      185    121.0
417    1174062         천호3동      183    162.0
37     1117058          효창동      182    157.0
365    1168061         대치2동      181     78.0
317    1159068        신대방2동      180    153.0
293    1156062         양평2동      179    138.0
111    1129055          삼선동      175    141.0
91     1123073         휘경2동      175    134.0
75     1121584         자양4동      175    132.0
407    1174052          상일동      174     62.0
43     1117066        이태원2동      171    151.0
334    1162072          조원동      170    141.0
64     1121571          화양동      168    154.0
184    1138059         응암2동      167    123.0
381    1171053         거여1동      167    118.0
311    1159063         사당2동      166    135.0
96     1126055         면목5동      165    127.0
112    1129057          동선동      163    132.0
38     1117059          용문동      163    158.0
200    1141066         홍은1동      163    108.0
70     1121578           능동      162    149.0
161    1135060         공릉2동      162     85.0
108    1126068         신내1동      162     88.0
322    1162058         낙성대동      162     99.0
380    1171052         풍납2동      160    111.0
212    1144063          신수동      160    128.0
191    1138069          진관동      159     11.0
325    1162061          중앙동      158    124.0
352    1165062         방배3동      153     81.0
16     1111071         숭인2동      152    145.0
20     1114058          장충동      150    145.0
314    1159065         사당5동      149    113.0
162    1135061         중계본동      149     91.0
240    1150052         등촌1동      148    127.0
74     1121584         자양3동      147     73.0
239    1150051          염창동      146    124.0
46     1117070          보광동      145    125.0
360    1168054         압구정동      144     44.0
54     1120059        금호1가동      144    125.0
169    1135064         상계2동      143     91.0
290    1156058          도림동      142    103.0
266    1153072         고척1동      140     77.0
204    1141071        북가좌1동      138     76.0
80     1123053          용두동      136     99.0
294    1156063         신길1동      136    106.0
35     1117056        원효로1동      135    124.0
143    1132051          창1동      135    109.0
303    1159051        노량진1동      135     70.0
25     1114063          약수동      133     74.0
92     1123074         이문1동      132    105.0
398    1171064          위례동      132      1.0
368    1168065         도곡1동      132     96.0
332    1162069          신림동      129    116.0
71     1121581          광장동      128     49.0
211    1144061          염리동      127     97.0
124    1129071         월곡1동      126     86.0
210    1144060          대흥동      126     91.0
343    1165054          잠원동      124     71.0
333    1162071          난향동      124     50.0
411    1174056         고덕2동      124     54.0
116    1129061          보문동      123     92.0
134    1130557         삼각산동      120      2.0
408    1174053         명일1동      119    104.0
7      1111060          가회동      116    110.0
336    1162074          삼성동      116     55.0
36     1117057        원효로2동      112     98.0
289    1156056         당산2동      111     76.0
125    1129072         월곡2동      110     75.0
316    1159067        신대방1동      110     87.0
301    1156071         대림2동      109     95.0
357    1168051          신사동      108     62.0
376    1168072         일원본동      106     95.0
50     1120055          사근동      106     91.0
209    1144059          용강동      105     80.0
115    1129060          안암동      103     85.0
156    1132071         방학3동      101     56.0
258    1150064         방화3동      101    100.0
375    1168070          세곡동       99     13.0
163    1135061         하계1동       99     63.0
232    1147061         신월6동       98     39.0
335    1162073          대학동       98     49.0
58     1120065       성수1가1동       96     69.0
60     1120067       성수2가1동       96     56.0
382    1171053         거여2동       95     76.0
149    1132052         도봉2동       94     57.0
128    1129078         장위3동       93     27.0
49     1120054          마장동       92     70.0
264    1153056         구로5동       92     60.0
379    1171051         풍납1동       92     72.0
286    1156053         영등포동       92     67.0
300    1156070         대림1동       90     59.0
117    1129062         정릉1동       90     62.0
410    1174055         고덕1동       89     36.0
296    1156066         신길4동       88     28.0
88     1123070         청량리동       88     62.0
288    1156055         당산1동       88     64.0
153    1132068         쌍문4동       87     61.0
193    1141055         북아현동       86     35.0
85     1123061        답십리2동       86     56.0
364    1168060         대치1동       86     11.0
298    1156068         신길6동       85     56.0
42     1117065        이태원1동       84     76.0
340    1165052         서초2동       84     55.0
274    1153080           항동       83     19.0
413    1174058         암사2동       81     70.0
199    1141065         홍제2동       81     50.0
221    1144074          상암동       81     34.0
30     1114068          중림동       80     25.0
250    1150060         가양1동       80     65.0
79     1123051          신설동       80     62.0
190    1138065          수색동       79     49.0
372    1168067         개포2동       78     35.0
347    1165058         반포3동       76     27.0
84     1123060        답십리1동       75     50.0
1      1111053          사직동       74     59.0
208    1144058          도화동       72     52.0
369    1168065         도곡2동       71     28.0
90     1123072         휘경1동       70     44.0
304    1159052        노량진2동       69     50.0
192    1141052          천연동       69     48.0
414    1174059         암사3동       69     48.0
33     1117053          남영동       67     60.0
61     1120069       성수2가3동       67     46.0
297    1156067         신길5동       66     50.0
137    1130560          번3동       66     26.0
114    1129059         돈암2동       65     35.0
342    1165053         서초4동       64      6.0
281    1154568         시흥2동       62     21.0
41     1117064         이촌2동       62     12.0
93     1123075         이문2동       62     26.0
62     1120072          송정동       61     58.0
39     1117062         한강로동       61     40.0
158    1135057         월계2동       61     17.0
57     1120064          옥수동       61     24.0
89     1123071          회기동       61     57.0
59     1120066       성수1가2동       59     34.0
319    1162054          청림동       57     19.0
56     1120062        금호4가동       57     33.0
295    1156065         신길3동       57     45.0
122    1129068         길음2동       56     17.0
51     1120056         행당1동       56     40.0
235    1147063         신정2동       55     37.0
27     1114065         신당5동       55     32.0
146    1132051          창4동       53      4.0
259    1153051         신도림동       53     15.0
83     1123057         전농2동       53     38.0
394    1171063         가락1동       52      NaN
292    1156061         양평1동       51     31.0
63     1120079          용답동       50     47.0
23     1114061          신당동       49     41.0
378    1168075          수서동       48     20.0
121    1129066         길음1동       45     14.0
291    1156060          문래동       45      6.0
52     1120057         행당2동       44     21.0
26     1114064          청구동       42     35.0
48     1120053       왕십리도선동       42     36.0
47     1120052        왕십리2동       41     16.0
167    1135062         중계4동       41     16.0
222    1147051          목1동       40     20.0
19     1114057           필동       40     20.0
113    1129058         돈암1동       38     19.0
242    1150053         등촌3동       37     31.0
15     1111070         숭인1동       37     31.0
356    1165066          내곡동       36     17.0
409    1174054         명일2동       35     25.0
28     1114066          동화동       35     24.0
206    1144055          아현동       35      7.0
238    1147068         신정7동       34     19.0
373    1168067         개포3동       33      1.0
234    1147062         신정1동       30     27.0
29     1114067          황학동       30     19.0
299    1156069         신길7동       25     22.0
371    1168066         개포1동       25     15.0
406    1174052          강일동       24      1.0
165    1135062         중계1동       24      NaN
405    1174051          강일동       23      NaN
12     1111067         창신1동       23     20.0
5      1111057          무악동       23     10.0
346    1165057         반포2동       20      NaN
202    1141069        남가좌1동       20     10.0
40     1117063         이촌1동       19      2.0
21     1114059          광희동       18     12.0
159    1135058         월계3동       18      2.0
164    1135061         하계2동       17      NaN
9      1111063      종로5.6가동       16     12.0
166    1135062       중계2.3동       16      NaN
17     1114054          회현동       16     12.0
14     1111069         창신3동       16      7.0
175    1135072        상계10동       13      1.0
172    1135069       상계6.7동       13      NaN
2      1111054          삼청동       12      9.0
251    1150060         가양2동       10      7.0
260    1153052         구로1동        8      1.0
403    1171069         잠실4동        7      NaN
18     1114055           명동        7      7.0
109    1126069         신내2동        7      7.0
402    1171068         잠실3동        7      NaN
8      1111061  종로1.2.3.4가동        6      3.0
226    1147055          목5동        5      4.0
287    1156054          여의동        5      4.0
174    1135071         상계9동        4      NaN
401    1171067         잠실2동        3      NaN
173    1135070         상계8동        3      NaN
404    1171071         잠실6동        3      3.0
252    1150060         가양3동        2      2.0
22     1114060         을지로동        2      1.0
387    1171056          오륜동        1      NaN
344    1165055         반포본동        1      NaN
397    1171064         문정2동        1      NaN

In [76]:
import pandas as pd

df_crime = pd.read_csv('crime_score.csv')
print(df_crime.columns.tolist())
print(df_crime.head(3))

['행정동코드', '자치구', '행정동', 'CRIME_SCORE']
      행정동코드  자치구  행정동  CRIME_SCORE
0  11010530  종로구  사직동           35
1  11010540  종로구  삼청동           36
2  11010550  종로구  부암동           26

In [78]:
df_crime = pd.read_csv('crime_score.csv')

# crime 코드 7자리로 변환
df_crime['hdong_code_7'] = df_crime['행정동코드'].astype(str).str[:7]

crime_dongs = set(df_crime['hdong_code_7'])
bldg_dongs = set(dong_count['hdong_code'])

# crime에는 있는데 건축물대장에 없는 동
missing_in_bldg = crime_dongs - bldg_dongs
print(f'crime에만 있는 동 ({len(missing_in_bldg)}개):')
print(df_crime[df_crime['hdong_code_7'].isin(missing_in_bldg)][['행정동코드', '자치구', '행정동']].to_string())

print()

# 건축물대장에는 있는데 crime에 없는 동
missing_in_crime = bldg_dongs - crime_dongs
print(f'건축물대장에만 있는 동 ({len(missing_in_crime)}개):')
print(dong_count[dong_count['hdong_code'].isin(missing_in_crime)][['hdong_code', 'hdong_name']].to_string())

crime에만 있는 동 (381개):
        행정동코드   자치구          행정동
0    11010530   종로구          사직동
1    11010540   종로구          삼청동
2    11010550   종로구          부암동
3    11010560   종로구          평창동
4    11010570   종로구          무악동
5    11010580   종로구          교남동
6    11010600   종로구          가회동
7    11010610   종로구  종로1·2·3·4가동
8    11010630   종로구      종로5·6가동
9    11010640   종로구          이화동
10   11010670   종로구         창신1동
11   11010680   종로구         창신2동
12   11010690   종로구         창신3동
13   11010700   종로구         숭인1동
14   11010710   종로구         숭인2동
15   11010720   종로구        청운효자동
16   11010730   종로구          혜화동
17   11020520    중구          소공동
18   11020540    중구          회현동
19   11020550    중구           명동
20   11020570    중구           필동
21   11020580    중구          장충동
22   11020590    중구          광희동
23   11020600    중구         을지로동
24   11020650    중구         신당5동
25   11020670    중구          황학동
26   11020680    중구          중림동
27   11020690    중구          신당동
28   11020700    중구          다산동
29   11020710    중구          약수동
30   11020720    중구          청구동
31   11020730    중구          동화동
32   11030510   용산구          후암동
33   11030520   용산구        용산2가동
34   11030530   용산구          남영동
35   11030570   용산구        원효로2동
36   11030580   용산구          효창동
37   11030590   용산구          용문동
38   11030630   용산구         이촌1동
39   11030640   용산구         이촌2동
40   11030650   용산구        이태원1동
41   11030660   용산구        이태원2동
42   11030690   용산구         서빙고동
43   11030700   용산구          보광동
44   11030710   용산구          청파동
45   11030720   용산구        원효로1동
46   11030730   용산구         한강로동
47   11030740   용산구          한남동
48   11040520   성동구        왕십리2동
49   11040540   성동구          마장동
50   11040550   성동구          사근동
51   11040560   성동구         행당1동
52   11040570   성동구         행당2동
53   11040580   성동구          응봉동
54   11040590   성동구        금호1가동
55   11040620   성동구        금호4가동
56   11040650   성동구       성수1가1동
57   11040660   성동구       성수1가2동
58   11040670   성동구       성수2가1동
59   11040680   성동구       성수2가3동
60   11040690   성동구          송정동
61   11040700   성동구          용답동
62   11040710   성동구       왕십리도선동
63   11040720   성동구      금호2·3가동
64   11040730   성동구          옥수동
65   11050530   광진구          화양동
66   11050540   광진구          군자동
67   11050550   광진구         중곡1동
68   11050560   광진구         중곡2동
69   11050570   광진구         중곡3동
70   11050580   광진구         중곡4동
71   11050590   광진구           능동
72   11050600   광진구         구의1동
73   11050610   광진구         구의2동
74   11050620   광진구         구의3동
75   11050630   광진구          광장동
76   11050640   광진구         자양1동
77   11050650   광진구         자양2동
78   11050660   광진구         자양3동
79   11050670   광진구         자양4동
80   11060710   동대문          회기동
81   11060720   동대문         휘경1동
82   11060730   동대문         휘경2동
83   11060800   동대문         청량리동
84   11060810   동대문          용신동
85   11060820   동대문          제기동
86   11060830   동대문         전농1동
87   11060840   동대문         전농2동
88   11060860   동대문        답십리2동
89   11060870   동대문         장안1동
90   11060880   동대문         장안2동
91   11060890   동대문         이문1동
92   11060900   동대문         이문2동
93   11060910   동대문        답십리1동
94   11070520   중랑구         면목2동
95   11070540   중랑구         면목4동
96   11070550   중랑구         면목5동
97   11070570   중랑구         면목7동
98   11070590   중랑구         상봉1동
99   11070600   중랑구         상봉2동
100  11070610   중랑구         중화1동
101  11070620   중랑구         중화2동
102  11070640   중랑구          묵1동
103  11070650   중랑구          묵2동
104  11070680   중랑구         망우3동
105  11070690   중랑구         신내1동
106  11070700   중랑구         신내2동
107  11070710   중랑구         면목본동
108  11070720   중랑구       면목3·8동
109  11070730   중랑구         망우본동
110  11080580   성북구         돈암1동
111  11080590   성북구         돈암2동
112  11080600   성북구          안암동
113  11080610   성북구          보문동
114  11080620   성북구         정릉1동
115  11080630   성북구         정릉2동
116  11080640   성북구         정릉3동
117  11080650   성북구         정릉4동
118  11080660   성북구         길음1동
119  11080680   성북구         길음2동
120  11080710   성북구         월곡1동
121  11080720   성북구         월곡2동
122  11080760   성북구         장위1동
123  11080770   성북구         장위2동
124  11080780   성북구         장위3동
125  11080810   성북구          성북동
126  11080820   성북구          삼선동
127  11080830   성북구          동선동
128  11080840   성북구          종암동
129  11080850   성북구          석관동
130  11090600   강북구          번1동
131  11090610   강북구          번2동
132  11090620   강북구          번3동
133  11090630   강북구         수유1동
134  11090640   강북구         수유2동
135  11090650   강북구         수유3동
136  11090690   강북구          삼양동
137  11090700   강북구          미아동
138  11090710   강북구          송중동
139  11090720   강북구          송천동
140  11090730   강북구         삼각산동
141  11090740   강북구          우이동
142  11090750   강북구          인수동
143  11100510   도봉구         쌍문1동
144  11100520   도봉구         쌍문2동
145  11100530   도봉구         쌍문3동
146  11100540   도봉구         쌍문4동
147  11100550   도봉구         방학1동
148  11100560   도봉구         방학2동
149  11100570   도봉구         방학3동
150  11100590   도봉구          창1동
151  11100600   도봉구          창2동
152  11100610   도봉구          창3동
153  11100620   도봉구          창4동
154  11100630   도봉구          창5동
155  11100640   도봉구         도봉1동
156  11100650   도봉구         도봉2동
158  11110520   노원구         월계2동
162  11110590   노원구         하계2동
167  11110660   노원구         상계2동
169  11110720   노원구         상계8동
170  11110730   노원구         상계9동
171  11110740   노원구        상계10동
172  11110760   노원구       상계3·4동
173  11110770   노원구       상계6·7동
174  11110780   노원구       중계2·3동
175  11110790   노원구         공릉1동
176  11120510   은평구          녹번동
177  11120520   은평구         불광1동
178  11120550   은평구         갈현1동
179  11120560   은평구         갈현2동
180  11120570   은평구          구산동
181  11120580   은평구          대조동
182  11120590   은평구         응암1동
183  11120600   은평구         응암2동
184  11120650   은평구         신사1동
185  11120660   은평구         신사2동
186  11120670   은평구          증산동
187  11120680   은평구          수색동
188  11120710   은평구          진관동
189  11120720   은평구         불광2동
190  11120730   은평구         응암3동
191  11120740   은평구          역촌동
192  11130520  서대문구          천연동
193  11130620  서대문구         홍제1동
194  11130640  서대문구         홍제3동
195  11130650  서대문구         홍제2동
196  11130660  서대문구         홍은1동
197  11130680  서대문구         홍은2동
198  11130690  서대문구        남가좌1동
199  11130700  서대문구        남가좌2동
200  11130710  서대문구        북가좌1동
201  11130720  서대문구        북가좌2동
202  11130730  서대문구          충현동
203  11130740  서대문구         북아현동
204  11130750  서대문구          신촌동
205  11130760  서대문구          연희동
212  11140690   마포구         망원1동
213  11140700   마포구         망원2동
214  11140710   마포구          연남동
215  11140720   마포구         성산1동
216  11140730   마포구         성산2동
217  11140740   마포구          상암동
218  11140750   마포구          도화동
219  11140760   마포구          서강동
220  11140770   마포구          공덕동
221  11140780   마포구          아현동
222  11150510   양천구          목1동
223  11150520   양천구          목2동
224  11150530   양천구          목3동
225  11150540   양천구          목4동
226  11150570   양천구         신월1동
227  11150580   양천구         신월2동
228  11150590   양천구         신월3동
229  11150600   양천구         신월4동
230  11150610   양천구         신월5동
231  11150620   양천구         신월6동
232  11150630   양천구         신월7동
233  11150640   양천구         신정1동
234  11150650   양천구         신정2동
235  11150660   양천구         신정3동
236  11150690   양천구         신정6동
237  11150700   양천구         신정7동
238  11150710   양천구          목5동
239  11150720   양천구         신정4동
240  11160510   강서구          염창동
241  11160520   강서구         등촌1동
242  11160530   강서구         등촌2동
243  11160540   강서구         등촌3동
244  11160550   강서구         화곡본동
245  11160570   강서구         화곡2동
246  11160580   강서구         화곡3동
247  11160590   강서구         화곡4동
248  11160610   강서구         화곡6동
249  11160630   강서구         화곡8동
250  11160650   강서구         가양2동
251  11160660   강서구         가양3동
252  11160670   강서구         발산1동
253  11160690   강서구          공항동
254  11160700   강서구         방화1동
255  11160710   강서구         방화2동
256  11160730   강서구         화곡1동
257  11160740   강서구         우장산동
258  11160751   강서구         가양1동
259  11160761   강서구         방화3동
262  11170540   구로구         구로3동
265  11170610   구로구         고척1동
269  11170670   구로구         오류1동
272  11170710   구로구         구로2동
273  11170720   구로구         개봉1동
274  11170730   구로구         오류2동
275  11170740   구로구           항동
276  11180510   금천구          가산동
277  11180520   금천구         독산1동
278  11180530   금천구         독산2동
279  11180540   금천구         독산3동
280  11180550   금천구         독산4동
281  11180570   금천구         시흥1동
282  11180580   금천구         시흥2동
283  11180590   금천구         시흥3동
284  11180600   금천구         시흥4동
285  11180610   금천구         시흥5동
286  11190540  영등포구          여의동
287  11190550  영등포구         당산1동
288  11190560  영등포구         당산2동
289  11190610  영등포구         양평1동
290  11190620  영등포구         양평2동
291  11190630  영등포구         신길1동
292  11190650  영등포구         신길3동
293  11190660  영등포구         신길4동
294  11190670  영등포구         신길5동
295  11190680  영등포구         신길6동
296  11190690  영등포구         신길7동
297  11190700  영등포구         대림1동
298  11190710  영등포구         대림2동
299  11190720  영등포구         대림3동
300  11190730  영등포구        영등포본동
301  11190740  영등포구         영등포동
302  11190750  영등포구          도림동
303  11190760  영등포구          문래동
309  11200630   동작구         사당1동
313  11200680   동작구          대방동
315  11200700   동작구        신대방2동
316  11200710   동작구          흑석동
318  11200730   동작구         사당2동
319  11210520   관악구         보라매동
320  11210540   관악구          청림동
321  11210570   관악구          행운동
322  11210580   관악구         낙성대동
323  11210610   관악구          중앙동
324  11210620   관악구          인헌동
325  11210630   관악구          남현동
326  11210640   관악구          서원동
327  11210650   관악구          신원동
328  11210660   관악구          서림동
329  11210680   관악구          신사동
330  11210690   관악구          신림동
331  11210710   관악구          난향동
332  11210720   관악구          조원동
333  11210730   관악구          대학동
334  11210780   관악구          은천동
335  11210790   관악구          성현동
336  11210800   관악구          청룡동
337  11210810   관악구          난곡동
338  11210820   관악구          삼성동
339  11210830   관악구          미성동
340  11220510   서초구         서초1동
341  11220520   서초구         서초2동
342  11220530   서초구         서초3동
343  11220540   서초구         서초4동
344  11220550   서초구          잠원동
345  11220560   서초구         반포본동
346  11220570   서초구         반포1동
347  11220580   서초구         반포2동
348  11220590   서초구         반포3동
349  11220600   서초구         반포4동
350  11220610   서초구         방배본동
351  11220620   서초구         방배1동
352  11220630   서초구         방배2동
353  11220640   서초구         방배3동
354  11220650   서초구         방배4동
355  11220660   서초구         양재1동
356  11220670   서초구         양재2동
357  11220680   서초구          내곡동
360  11230520   강남구         논현1동
362  11230580   강남구         삼성1동
363  11230590   강남구         삼성2동
365  11230630   강남구         대치4동
366  11230640   강남구         역삼1동
369  11230670   강남구         도곡2동
370  11230680   강남구         개포1동
375  11230760   강남구          세곡동
376  11230770   강남구         압구정동
377  11230780   강남구          청담동
378  11230790   강남구         대치2동
379  11230800   강남구         개포2동
380  11240510   송파구         풍납1동
381  11240520   송파구         풍납2동
382  11240530   송파구         거여1동
383  11240540   송파구         거여2동
384  11240550   송파구         마천1동
385  11240560   송파구         마천2동
386  11240570   송파구         방이1동
387  11240580   송파구         방이2동
388  11240590   송파구          오륜동
389  11240600   송파구          오금동
390  11240610   송파구         송파1동
391  11240620   송파구         송파2동
392  11240630   송파구          석촌동
393  11240640   송파구          삼전동
394  11240650   송파구         가락본동
395  11240660   송파구         가락1동
396  11240670   송파구         가락2동
397  11240680   송파구         문정1동
398  11240690   송파구         문정2동
399  11240710   송파구         잠실본동
400  11240750   송파구         잠실4동
401  11240770   송파구         잠실6동
402  11240780   송파구         잠실7동
403  11240790   송파구         잠실2동
404  11240800   송파구         잠실3동
405  11240810   송파구          장지동
406  11240820   송파구          위례동
407  11250530   강동구         명일1동
408  11250540   강동구         명일2동
409  11250550   강동구         고덕1동
410  11250560   강동구         고덕2동
411  11250580   강동구         암사2동
412  11250590   강동구         암사3동
413  11250610   강동구         천호1동
414  11250630   강동구         천호3동
415  11250650   강동구         성내1동
416  11250660   강동구         성내2동
417  11250670   강동구         성내3동
418  11250700   강동구         둔촌1동
419  11250710   강동구         둔촌2동
420  11250720   강동구         암사1동
421  11250730   강동구         천호2동
422  11250740   강동구           길동
423  11250750   강동구          강일동
424  11250760   강동구          상일동

건축물대장에만 있는 동 (340개):
    hdong_code hdong_name
186    1138062        역촌동
249    1150059       화곡본동
392    1171061        삼전동
391    1171060        석촌동
243    1150054       화곡1동
205    1141072      북가좌2동
142    1130566        인수동
389    1171058       송파1동
248    1150059       화곡8동
181    1138056        구산동
400    1171065       잠실본동
223    1147052        목2동
180    1138055       갈현2동
178    1138053       불광2동
237    1147065       신정4동
176    1138051        녹번동
386    1171056       방이2동
308    1159056       상도4동
196    1141061        연희동
201    1141068       홍은2동
177    1138052       불광1동
69     1121577       중곡4동
233    1147061       신월7동
412    1174057       암사1동
187    1138063       신사1동
367    1168064       역삼1동
388    1171057        오금동
185    1138060       응암3동
179    1138055       갈현1동
141    1130564        우이동
182    1138057        대조동
307    1159055       상도3동
77     1121586       구의2동
219    1144072       성산1동
246    1150057       화곡4동
273    1153079        수궁동
355    1165065       양재2동
326    1162062        인헌동
97     1126056       면목본동
338    1162077        난곡동
148    1132052       도봉1동
416    1174061       천호2동
144    1132051        창2동
421    1174068         길동
138    1130561       수유1동
150    1132066       쌍문1동
215    1144068        합정동
244    1150055       화곡2동
155    1132070       방학2동
216    1144069       망원1동
132    1130554        송중동
136    1130560        번2동
305    1159053       상도1동
126    1129076       장위1동
354    1165065       양재1동
225    1147054        목4동
415    1174060       천호1동
353    1165062       방배4동
118    1129063       정릉2동
341    1165053       서초3동
214    1144066        서교동
224    1147053        목3동
358    1168052       논현1동
270    1153076       개봉3동
130    1130553        미아동
324    1162060        은천동
247    1150059       화곡6동
183    1138058       응암1동
337    1162076        미성동
44     1117068        한남동
76     1121585       구의1동
395    1171063       가락2동
268    1153074       개봉1동
420    1174066       성내3동
269    1153075       개봉2동
310    1159062       사당1동
131    1130553        삼양동
160    1135059       공릉1동
328    1162064        서원동
73     1121583       자양2동
207    1144056        공덕동
140    1130563       수유3동
278    1154563       독산3동
104    1126062        묵1동
366    1168063       대치4동
396    1171064       문정1동
72     1121582       자양1동
67     1121575       중곡2동
217    1144070       망원2동
218    1144071        연남동
24     1114062        다산동
139    1130562       수유2동
129    1129081        석관동
227    1147056       신월1동
318    1162052       보라매동
350    1165060       방배1동
374    1168069       개포4동
280    1154567       시흥1동
133    1130555        송천동
283    1154570       시흥4동
254    1150061       우장산동
359    1168053       논현2동
120    1129065       정릉4동
315    1159066        대방동
384    1171055       마천2동
241    1150053       등촌2동
393    1171062       가락본동
277    1154562       독산2동
188    1138063       신사2동
348    1165058       반포4동
255    1150062        공항동
151    1132067       쌍문2동
418    1174064       성내1동
256    1150063       방화1동
327    1162063        남현동
272    1153078       오류2동
383    1171054       마천1동
103    1126061       중화2동
419    1174065       성내2동
363    1168059       삼성2동
351    1165061       방배2동
220    1144073       성산2동
106    1126065       망우본동
323    1162059        청룡동
228    1147057       신월2동
110    1129052        성북동
399    1171064        장지동
94     1126052       면목2동
154    1132069       방학1동
313    1159065       사당4동
123    1129070        종암동
197    1141062       홍제1동
231    1147060       신월5동
203    1141070      남가좌2동
253    1150061       발산1동
385    1171056       방이1동
245    1150056       화곡3동
282    1154569       시흥3동
422    1174070       둔촌2동
263    1153055       구로4동
102    1126060       중화1동
157    1135056       월계1동
78     1121587       구의3동
284    1154571       시흥5동
101    1126059       상봉2동
321    1162057        행운동
152    1132068       쌍문3동
349    1165059       방배본동
257    1150064       방화2동
81     1123054        제기동
267    1153073       고척2동
98     1126057     면목3.8동
345    1165056       반포1동
213    1144065        서강동
68     1121576       중곡3동
66     1121574       중곡1동
279    1154564       독산4동
194    1141056        충현동
370    1168065       역삼2동
230    1147059       신월4동
119    1129064       정릉3동
312    1159064       사당3동
170    1135066     상계3.4동
261    1153053       구로2동
107    1126066       망우3동
105    1126063        묵2동
330    1162066        서림동
229    1147058       신월3동
262    1153054       구로3동
377    1168073       일원1동
189    1138064        증산동
168    1135063       상계1동
127    1129077       장위2동
361    1168056        청담동
285    1156051      영등포본동
65     1121573        군자동
55     1120061    금호2.3가동
100    1126058       상봉1동
302    1156072       대림3동
145    1132051        창3동
3      1111055        부암동
320    1162056        성현동
271    1153077       오류1동
276    1154561       독산1동
171    1135067       상계5동
195    1141058        신촌동
198    1141064       홍제3동
331    1162068        신사동
99     1126057       면목7동
306    1159054       상도2동
82     1123056       전농1동
135    1130559        번1동
236    1147064       신정3동
53     1120058        응봉동
329    1162065        신원동
309    1159060        흑석동
339    1165051       서초1동
390    1171059       송파2동
13     1111068       창신2동
362    1168058       삼성1동
147    1132051        창5동
265    1153059       가리봉동
95     1126054       면목4동
275    1154551        가산동
417    1174062       천호3동
37     1117058        효창동
365    1168061       대치2동
317    1159068      신대방2동
293    1156062       양평2동
111    1129055        삼선동
75     1121584       자양4동
407    1174052        상일동
43     1117066      이태원2동
334    1162072        조원동
64     1121571        화양동
184    1138059       응암2동
381    1171053       거여1동
311    1159063       사당2동
96     1126055       면목5동
112    1129057        동선동
38     1117059        용문동
200    1141066       홍은1동
70     1121578         능동
161    1135060       공릉2동
108    1126068       신내1동
322    1162058       낙성대동
380    1171052       풍납2동
212    1144063        신수동
191    1138069        진관동
325    1162061        중앙동
352    1165062       방배3동
16     1111071       숭인2동
20     1114058        장충동
314    1159065       사당5동
162    1135061       중계본동
240    1150052       등촌1동
74     1121584       자양3동
239    1150051        염창동
360    1168054       압구정동
54     1120059      금호1가동
169    1135064       상계2동
290    1156058        도림동
266    1153072       고척1동
204    1141071      북가좌1동
294    1156063       신길1동
143    1132051        창1동
303    1159051      노량진1동
92     1123074       이문1동
398    1171064        위례동
368    1168065       도곡1동
332    1162069        신림동
71     1121581        광장동
211    1144061        염리동
124    1129071       월곡1동
210    1144060        대흥동
343    1165054        잠원동
333    1162071        난향동
411    1174056       고덕2동
116    1129061        보문동
134    1130557       삼각산동
408    1174053       명일1동
336    1162074        삼성동
36     1117057      원효로2동
289    1156056       당산2동
125    1129072       월곡2동
316    1159067      신대방1동
301    1156071       대림2동
357    1168051        신사동
376    1168072       일원본동
209    1144059        용강동
115    1129060        안암동
156    1132071       방학3동
258    1150064       방화3동
375    1168070        세곡동
163    1135061       하계1동
232    1147061       신월6동
335    1162073        대학동
382    1171053       거여2동
149    1132052       도봉2동
128    1129078       장위3동
264    1153056       구로5동

In [79]:
crime_names = set(df_crime['행정동'])
bldg_names = set(dong_count['hdong_name'])

missing_in_bldg = crime_names - bldg_names
missing_in_crime = bldg_names - crime_names

print(f'crime에만 있는 동 ({len(missing_in_bldg)}개):')
print(sorted(missing_in_bldg))

print(f'\n건축물대장에만 있는 동 ({len(missing_in_crime)}개):')
print(sorted(missing_in_crime))

crime에만 있는 동 (12개):
['금호2·3가동', '둔촌1동', '면목3·8동', '상계3·4동', '상계6·7동', '소공동', '신정6동', '용신동', '잠실7동', '종로1·2·3·4가동', '종로5·6가동', '중계2·3동']

건축물대장에만 있는 동 (9개):
['금호2.3가동', '면목3.8동', '상계3.4동', '상계6.7동', '신설동', '용두동', '종로1.2.3.4가동', '종로5.6가동', '중계2.3동']

In [80]:
# 특수문자 통일 후 재비교
def normalize(name):
    return name.replace('·', '.').replace(' ', '')

df_crime['행정동_norm'] = df_crime['행정동'].apply(normalize)
dong_count['hdong_name_norm'] = dong_count['hdong_name'].apply(normalize)

crime_names_norm = set(df_crime['행정동_norm'])
bldg_names_norm = set(dong_count['hdong_name_norm'])

missing_in_bldg = crime_names_norm - bldg_names_norm
missing_in_crime = bldg_names_norm - crime_names_norm

print(f'crime에만 있는 동 ({len(missing_in_bldg)}개):')
print(sorted(missing_in_bldg))

print(f'\n건축물대장에만 있는 동 ({len(missing_in_crime)}개):')
print(sorted(missing_in_crime))

crime에만 있는 동 (5개):
['둔촌1동', '소공동', '신정6동', '용신동', '잠실7동']

건축물대장에만 있는 동 (2개):
['신설동', '용두동']

In [84]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# shapefile 로드
gdf_hdong = gpd.read_file('../data/hdong_data/bnd_dong_11_2025_2Q/bnd_dong_11_2025_2Q.shp')
gdf_hdong = gdf_hdong.to_crs(epsg=4326)
gdf_hdong = gdf_hdong.rename(columns={'ADM_CD': 'hdong_code', 'ADM_NM': 'hdong_name'})

# df_geo 로드 (좌표 있는 것만)
df_geo = pd.read_csv('../data/checkpoint.csv')
df_valid = df_geo[df_geo['lng'].notna() & df_geo['lat'].notna()].copy()

# GeoDataFrame 변환
gdf_bldg = gpd.GeoDataFrame(
    df_valid,
    geometry=gpd.points_from_xy(df_valid['lng'], df_valid['lat']),
    crs='EPSG:4326'
)

# sjoin
gdf_joined = gpd.sjoin(
    gdf_bldg,
    gdf_hdong[['hdong_code', 'hdong_name', 'geometry']],
    how='left',
    predicate='within'
)

# 통폐합 규칙 적용
dong_rename = {
    '상일1동': '상일동',
    '상일2동': '강일동',
}
gdf_joined['hdong_name_right'] = gdf_joined['hdong_name_right'].replace(dong_rename)

# shapefile 기반 행정동별 건물 수
dong_count_shp = gdf_joined.groupby(['hdong_code_right', 'hdong_name_right']).size().reset_index(name='건물수')
dong_count_shp = dong_count_shp.sort_values('건물수', ascending=False)

print(f'총 행정동 수: {len(dong_count_shp)}')
print(f'매핑 실패: {gdf_joined["hdong_code_right"].isna().sum():,}건')
print(dong_count_shp.to_string())

총 행정동 수: 422
매핑 실패: 0건
    hdong_code_right hdong_name_right   건물수
190         11120740              역촌동  1179
242         11160550             화곡본동  1080
391         11240640              삼전동  1079
390         11240630              석촌동  1058
254         11160730             화곡1동  1041
200         11130720            북가좌2동   814
141         11090750              인수동   796
388         11240610             송파1동   773
247         11160630             화곡8동   759
179         11120570              구산동   747
397         11240710             잠실본동   741
222         11150520              목2동   739
178         11120560             갈현2동   711
237         11150720             신정4동   708
188         11120720             불광2동   708
175         11120510              녹번동   674
385         11240580             방이2동   662
306         11200560             상도4동   640
204         11130760              연희동   635
196         11130680             홍은2동   630
176         11120520             불광1동   629
69          11050580             중곡4동   622
231         11150630             신월7동   613
416         11250720             암사1동   611
183         11120650             신사1동   602
364         11230640             역삼1동   578
387         11240600              오금동   575
189         11120730             응암3동   566
177         11120550             갈현1동   551
140         11090740              우이동   544
180         11120580              대조동   539
72          11050610             구의2동   536
305         11200550             상도3동   536
214         11140720             성산1동   532
245         11160590             화곡4동   519
268         11170690              수궁동   517
354         11220670             양재2동   513
322         11210620              인헌동   512
106         11070710             면목본동   510
335         11210810              난곡동   507
154         11100640             도봉1동   501
417         11250730             천호2동   498
150         11100600              창2동   492
418         11250740               길동   492
142         11100510             쌍문1동   491
132         11090630             수유1동   491
210         11140680              합정동   488
243         11160570             화곡2동   487
147         11100560             방학2동   483
137         11090710              송중동   481
211         11140690             망원1동   481
130         11090610              번2동   478
303         11200530             상도1동   475
43          11030710              청파동   470
121         11080760             장위1동   469
353         11220660             양재1동   467
224         11150540              목4동   451
410         11250610             천호1동   444
352         11220650             방배4동   443
114         11080630             정릉2동   440
340         11220530             서초3동   437
209         11140660              서교동   435
223         11150530              목3동   435
358         11230520             논현1동   431
266         11170650             개봉3동   430
136         11090700              미아동   424
332         11210780              은천동   423
246         11160610             화곡6동   421
46          11030740              한남동   415
181         11120590             응암1동   415
337         11210830              미성동   415
71          11050600             구의1동   413
394         11240670             가락2동   411
271         11170720             개봉1동   403
414         11250670             성내3동   400
265         11170640             개봉2동   392
307         11200630             사당1동   388
135         11090690              삼양동   387
174         11110790             공릉1동   384
324         11210640              서원동   383
76          11050650             자양2동   380
134         11090650             수유3동   377
219         11140770              공덕동   377
277         11180540             독산3동   375
101         11070640              묵1동   374
363         11230630             대치4동   372
31          11030510              후암동   370
395         11240680             문정1동   369
3           11010560              평창동   366
75          11050640             자양1동   364
212         11140700             망원2동   361
67          11050560             중곡2동   361
213         11140710              연남동   359
88          11060870             장안1동   359
27          11020700              다산동   358
133         11090640             수유2동   357
128         11080850              석관동   356
225         11150570             신월1동   355
317         11210520             보라매동   355
349         11220620             방배1동   352
369         11230710             개포4동   348
279         11180570             시흥1동   347
138         11090720              송천동   347
282         11180600             시흥4동   345
255         11160740             우장산동   344
359         11230530             논현2동   343
116         11080650             정릉4동   338
16          11010730              혜화동   334
311         11200680              대방동   332
383         11240560             마천2동   331
240         11160530             등촌2동   329
392         11240650             가락본동   328
15          11010720            청운효자동   326
184         11120660             신사2동   325
276         11180530             독산2동   325
251         11160690              공항동   320
347         11220600             반포4동   319
412         11250650             성내1동   316
143         11100520             쌍문2동   316
252         11160700             방화1동   313
323         11210630              남현동   308
272         11170730             오류2동   308
382         11240550             마천1동   306
100         11070620             중화2동   304
413         11250660             성내2동   304
361         11230590             삼성2동   303
350         11220630             방배2동   302
108         11070730             망우본동   298
215         11140730             성산2동   298
334         11210800              청룡동   294
226         11150580             신월2동   293
32          11030520            용산2가동   291
124         11080810              성북동   290
402         11240810              장지동   290
146         11100550             방학1동   289
93          11070520             면목2동   289
309         11200660             사당4동   288
127         11080840              종암동   286
192         11130620             홍제1동   280
229         11150610             신월5동   279
198         11130700            남가좌2동   277
250         11160670             발산1동   276
384         11240570             방이1동   275
244         11160580             화곡3동   271
415         11250710             둔촌2동   269
281         11180590             시흥3동   269
261         11170550             구로4동   268
89          11060880             장안2동   267
99          11070610             중화1동   266
156         11110510             월계1동   264
283         11180610             시흥5동   259
73          11050620             구의3동   259
98          11070600             상봉2동   258
319         11210570              행운동   257
144         11100530             쌍문3동   256
348         11220610             방배본동   255
253         11160710             방화2동   254
84          11060820              제기동   253
264         11170620             고척2동   251
107         11070720           면목3·8동   250
344         11220570             반포1동   250
218         11140760              서강동   249
66          11050550             중곡1동   248
68          11050570             중곡3동   248
278         11180550             독산4동   245
201         11130730              충현동   244
115         11080640             정릉3동   244
365         11230650             역삼2동   244
228         11150600             신월4동   242
167         11110690             상계5동   242
308         11200650             사당3동   239
270         11170710             구로2동   238
103         11070680             망우3동   236
102         11070650              묵2동   236
5           11010580              교남동   235
227         11150590             신월3동   232
326         11210660              서림동   232
260         11170540             구로3동   231
371         11230730             일원1동   231
185         11120670              증산동   230
122         11080770             장위2동   227
165         11110650             상계1동   227
375         11230780              청담동   223
9           11010640              이화동   222
298         11190730            영등포본동   222
65          11050540              군자동   220
97          11070590             상봉1동   218
62          11040720          금호2·3가동   218
297         11190720             대림3동   217
151         11100610              창3동   217
83          11060810              용신동   216
333         11210790              성현동   216
2           11010550              부암동   216
267         11170670             오류1동   214
275         11180520             독산1동   213
193         11130640             홍제3동   212
203         11130750              신촌동   212
171         11110760           상계3·4동   209
327         11210680              신사동   209
96          11070570             면목7동   206
304         11200540             상도2동   205
85          11060830             전농1동   204
129         11090600              번1동   204
234         11150660             신정3동   203
52          11040580              응봉동   202
325         11210650              신원동   201
314         11200710              흑석동   200
338         11220510             서초1동   198
389         11240620             송파2동   196
11          11010680             창신2동   194
360         11230580             삼성1동   192
153         11100630              창5동   190
41          11030690             서빙고동   189
94          11070540             면목4동   188
269         11170700             가리봉동   188
274         11180510              가산동   185
35          11030580              효창동   183
411         11250630             천호3동   183
376         11230790             대치2동   181
313         11200700            신대방2동   180
288         11190620             양평2동   179
78          11050670             자양4동   175
81          11060730             휘경2동   175
125         11080820              삼선동   175
420         11250760              상일동   174
40          11030660            이태원2동   171
330         11210720              조원동   170
64          11050530              화양동   168
380         11240530             거여1동   167
182         11120600             응암2동   167
316         11200730             사당2동   166
95          11070550             면목5동   165
36          11030590              용문동   163
195         11130660             홍은1동   163
320         11210580             낙성대동   162
70          11050590               능동   162
104         11070690             신내1동   162
126         11080830              동선동   162
159         11110560             공릉2동   162
379         11240520             풍납2동   160
208         11140630              신수동   160
187         11120710              진관동   159
321         11210610              중앙동   158
351         11220640             방배3동   153
14          11010710             숭인2동   152
20          11020580              장충동   149
162         11110600             중계본동   149
310         11200670             사당5동   149
239         11160520             등촌1동   148
77          11050660             자양3동   147
238         11160510              염창동   146
42          11030700              보광동   145
374         11230770             압구정동   144
53          11040590            금호1가동   144
166         11110660             상계2동   143
300         11190750              도림동   142
263         11170610             고척1동   140
199         11130710            북가좌1동   138
289         11190630             신길1동   136
44          11030720            원효로1동   135
149         11100590              창1동   135
315         11200720            노량진1동   135
28          11020710              약수동   133
90          11060890             이문1동   132
403         11240820              위례동   132
366         11230660             도곡1동   132
328         11210690              신림동   129
74          11050630              광장동   128
207         11140610              염리동   127
206         11140600              대흥동   126
119         11080710             월곡1동   126
329         11210710              난향동   124
407         11250560             고덕2동   124
342         11220550              잠원동   124
112         11080610              보문동   123
139         11090730             삼각산동   120
404         11250530             명일1동   119
6           11010600              가회동   116
336         11210820              삼성동   116
34          11030570            원효로2동   112
286         11190560             당산2동   111
120         11080720             월곡2동   110
312         11200690            신대방1동   110
296         11190710             대림2동   109
356         11230510              신사동   108
49          11040550              사근동   106
370         11230720             일원본동   106
205         11140590              용강동   105
111         11080600              안암동   103
148         11100570             방학3동   101
257         11160761             방화3동   101
160         11110580             하계1동    99
373         11230760              세곡동    99
230         11150620             신월6동    98
331         11210730              대학동    98
57          11040670           성수2가1동    96
55          11040650           성수1가1동    96
381         11240540             거여2동    95
155         11100650             도봉2동    94
123         11080780             장위3동    93
262         11170560             구로5동    92
48          11040540              마장동    92
378         11240510             풍납1동    92
299         11190740             영등포동    92
295         11190700             대림1동    90
113         11080620             정릉1동    89
406         11250550             고덕1동    89
82          11060800             청량리동    89
291         11190660             신길4동    88
285         11190550             당산1동    88
145         11100540             쌍문4동    87
87          11060860            답십리2동    86
362         11230600             대치1동    86
202         11130740             북아현동    86
293         11190680             신길6동    85
39          11030650            이태원1동    84
339         11220520             서초2동    84
273         11170740               항동    83
216         11140740              상암동    81
408         11250580             암사2동    81
194         11130650             홍제2동    81
25          11020680              중림동    80
256         11160751             가양1동    80
186         11120680              수색동    79
377         11230800             개포2동    78
346         11220590             반포3동    76
92          11060910            답십리1동    75
0           11010530              사직동    74
217         11140750              도화동    72
367         11230670             도곡2동    71
80          11060720             휘경1동    70
302         11200520            노량진2동    69
409         11250590             암사3동    69
191         11130520              천연동    69
110         11080590             돈암2동    68
58          11040680           성수2가3동    67
33          11030530              남영동    67
292         11190670             신길5동    66
131         11090620              번3동    66
341         11220540             서초4동    64
280         11180580             시흥2동    62
38          11030640             이촌2동    62
91          11060900             이문2동    62
63          11040730              옥수동    61
79          11060710              회기동    61
59          11040690              송정동    61
157         11110520             월계2동    61
45          11030730             한강로동    61
56          11040660           성수1가2동    59
54          11040620            금호4가동    57
23          11020650             신당5동    57
290         11190650             신길3동    57
318         11210540              청림동    57
50          11040560             행당1동    56
118         11080680             길음2동    56
233         11150650             신정2동    55
86          11060840             전농2동    53
152         11100620              창4동    53
258         11170510             신도림동    53
393         11240660             가락1동    52
287         11190610             양평1동    51
60          11040700              용답동    50
26          11020690              신당동    49
372         11230750              수서동    48
117         11080660             길음1동    45
301         11190760              문래동    45
51          11040570             행당2동    44
61          11040710           왕십리도선동    42
29          11020720              청구동    42
164         11110640             중계4동    41
47          11040520            왕십리2동    41
19          11020570               필동    41
221         11150510              목1동    40
109         11080580             돈암1동    38
13          11010700             숭인1동    37
241         11160540             등촌3동    37
355         11220680              내곡동    36
220         11140780              아현동    35
405         11250540             명일2동    35
235         11150700             신정7동    34
30          11020730              동화동    33
357         11230511             개포3동    33
24          11020670              황학동    30
232         11150640             신정1동    30
368         11230680             개포1동    25
294         11190690             신길7동    25
421         11250770              강일동    24
163         11110610             중계1동    24
4           11010570              무악동    23
419         11250750              강일동    23
10          11010670             창신1동    23
197         11130690            남가좌1동    20
345         11220580             반포2동    20
37          11030630             이촌1동    19
21          11020590              광희동    18
158         11110530             월계3동    18
12          11010690             창신3동    17
161         11110590             하계2동    17
17          11020540              회현동    16
173         11110780           중계2·3동    16
8           11010630          종로5·6가동    16
170         11110740            상계10동    13
172         11110770           상계6·7동    13
1           11010540              삼청동    12
248         11160650             가양2동    10
259         11170520             구로1동     8
18          11020550               명동     7
105         11070700             신내2동     7
398         11240750             잠실4동     7
401         11240800             잠실3동     7
7           11010610      종로1·2·3·4가동     6
284         11190540              여의동     5
236         11150710              목5동     5
169         11110730             상계9동     4
168         11110720             상계8동     3
400         11240790             잠실2동     3
399         11240770             잠실6동     3
22          11020600             을지로동     2
249         11160660             가양3동     2
396         11240690             문정2동     1
343         11220560             반포본동     1
386         11240590              오륜동     1

In [83]:
print(gdf_joined.columns.tolist())

['idx', 'lng', 'lat', 'hdong_code_left', 'hdong_name_left', 'b_code', 'geometry', 'index_right', 'hdong_code_right', 'hdong_name_right']

In [85]:
# shapefile 기반 동코드 (원본 그대로)
shp_codes = set(dong_count_shp['hdong_code_right'].astype(str))

# crime 동코드 (원본 8자리)
crime_codes = set(df_crime['행정동코드'].astype(str))

missing_in_shp = crime_codes - shp_codes
missing_in_crime = shp_codes - crime_codes

print(f'crime에만 있는 동 ({len(missing_in_shp)}개):')
print(df_crime[df_crime['행정동코드'].astype(str).isin(missing_in_shp)][['행정동코드', '행정동']].to_string())

print(f'\nshapefile에만 있는 동 ({len(missing_in_crime)}개):')
print(dong_count_shp[dong_count_shp['hdong_code_right'].astype(str).isin(missing_in_crime)][['hdong_code_right', 'hdong_name_right', '건물수']].to_string())

crime에만 있는 동 (4개):
        행정동코드   행정동
17   11020520   소공동
236  11150690  신정6동
402  11240780  잠실7동
418  11250700  둔촌1동

shapefile에만 있는 동 (1개):
    hdong_code_right hdong_name_right  건물수
421         11250770              강일동   24

In [115]:
import geopandas as gpd
import pandas as pd
from shapely.geometry import Point

# 1. shapefile 로드
gdf_hdong = gpd.read_file('../data/hdong_data/bnd_dong_11_2025_2Q/bnd_dong_11_2025_2Q.shp')
gdf_hdong = gdf_hdong.to_crs(epsg=4326)
gdf_hdong = gdf_hdong.rename(columns={'ADM_CD': 'hdong_code', 'ADM_NM': 'hdong_name'})

# 2. checkpoint 로드 후 좌표 있는 것만
df_geo = pd.read_csv('../data/checkpoint.csv')
df_valid = df_geo[df_geo['lng'].notna() & df_geo['lat'].notna()].copy()

# 3. GeoDataFrame 변환
gdf_bldg = gpd.GeoDataFrame(
    df_valid,
    geometry=gpd.points_from_xy(df_valid['lng'], df_valid['lat']),
    crs='EPSG:4326'
)

# 4. sjoin
gdf_joined = gpd.sjoin(
    gdf_bldg,
    gdf_hdong[['hdong_code', 'hdong_name', 'geometry']],
    how='left',
    predicate='within'
)

# 5. 통폐합 규칙 적용
dong_rename = {'상일1동': '상일동', '상일2동': '강일동'}
code_rename = {'11250760': '11250760', '11250770': '11250750'}

gdf_joined['hdong_name_right'] = gdf_joined['hdong_name_right'].replace(dong_rename)
gdf_joined['hdong_code_right'] = gdf_joined['hdong_code_right'].astype(str).replace(code_rename)


# 6. 원본 df와 merge (좌표 있는 것만)
df_geo_valid = df_geo[df_geo['lng'].notna() & df_geo['lat'].notna()].set_index('idx')
df_final = df.loc[df.index.isin(df_geo_valid.index)].join(df_geo_valid[['lng', 'lat', 'b_code']])
df_final['hdong_code'] = gdf_joined.set_index('idx')['hdong_code_right']
df_final['hdong_name'] = gdf_joined.set_index('idx')['hdong_name_right']

# 7. 컬럼명 정리 및 PNU 생성
df_final = df_final.rename(columns={
    '사용승인일자': 'SYDATE',
    '대지면적':    'total_area',
    '세대수':      'total_units'
})

df_final['b_code']     = df_final['b_code'].astype(str).str.split('.').str[0].str.zfill(10)
df_final['bun_padded'] = df_final['주지번'].astype(str).str.split('.').str[0].str.zfill(4)
df_final['ji_padded']  = df_final['부지번'].astype(str).str.split('.').str[0].str.zfill(4)
df_final['PNU']        = df_final['b_code'] + '0' + df_final['bun_padded'] + df_final['ji_padded']
# 구 이름 추출
df_final['gu_name'] = df_final['대지위치'].str.extract(r'서울특별시\s+(\S+구)')

# 8. 최종 저장
cols = ['대지위치', 'gu_name', 'hdong_code', 'hdong_name',
        'SYDATE', 'total_area', 'total_units',
        'PNU', 'lng', 'lat']

df_final[cols].to_csv('../data/건축물대장_빅캠반입용.csv',
                      index=False, encoding='utf-8-sig')

print(f'반입용 데이터: {df_final[cols].shape}')
print(df_final[cols].isnull().sum())
print(f'\n총 행정동 수: {df_final["hdong_code"].nunique()}')

반입용 데이터: (99721, 10)
대지위치              0
gu_name           0
hdong_code        0
hdong_name        0
SYDATE            0
total_area     5401
total_units    2688
PNU               0
lng               0
lat               0
dtype: int64

총 행정동 수: 421

In [99]:
# 노후도용: hdong_code 있는 것 (SYDATE 결측 0이니까 그대로)
old_count = gdf_joined[gdf_joined['hdong_code_right'].notna()].groupby(
    ['hdong_code_right', 'hdong_name_right']).size().reset_index(name='노후도_건물수')

# 집적도용: hdong_code 있고 total_area > 0 이고 total_units notna
df_final_valid = df_final[
    df_final['hdong_code'].notna() &
    (df_final['total_area'] > 0) &
    df_final['total_area'].notna() &
    df_final['total_units'].notna()
]
density_count = df_final_valid.groupby(['hdong_code', 'hdong_name']).size().reset_index(name='집적도_건물수')

# 합쳐서 비교
dong_count_final = pd.merge(
    old_count,
    density_count,
    left_on='hdong_code_right',
    right_on='hdong_code',
    how='outer'
)

dong_count_final = dong_count_final.sort_values('노후도_건물수', ascending=False)
print(f'총 행정동 수: {len(dong_count_final)}')
print(dong_count_final[['hdong_code_right', 'hdong_name_right', '노후도_건물수', '집적도_건물수']].to_string())

총 행정동 수: 421
    hdong_code_right hdong_name_right  노후도_건물수  집적도_건물수
190         11120740              역촌동     1179   1085.0
242         11160550             화곡본동     1080   1048.0
391         11240640              삼전동     1079   1032.0
390         11240630              석촌동     1058   1010.0
254         11160730             화곡1동     1041   1014.0
200         11130720            북가좌2동      814    703.0
141         11090750              인수동      796    585.0
388         11240610             송파1동      773    732.0
247         11160630             화곡8동      759    734.0
179         11120570              구산동      747    664.0
397         11240710             잠실본동      741    714.0
222         11150520              목2동      739    644.0
178         11120560             갈현2동      711    643.0
237         11150720             신정4동      708    647.0
188         11120720             불광2동      708    585.0
175         11120510              녹번동      674    567.0
385         11240580             방이2동      662    586.0
306         11200560             상도4동      640    558.0
204         11130760              연희동      635    426.0
196         11130680             홍은2동      630    442.0
176         11120520             불광1동      629    484.0
69          11050580             중곡4동      622    577.0
231         11150630             신월7동      613    146.0
416         11250720             암사1동      611    574.0
183         11120650             신사1동      602    519.0
364         11230640             역삼1동      578    527.0
387         11240600              오금동      575    402.0
189         11120730             응암3동      566    477.0
177         11120550             갈현1동      551    467.0
140         11090740              우이동      544    454.0
180         11120580              대조동      539    503.0
72          11050610             구의2동      536    481.0
305         11200550             상도3동      536    485.0
214         11140720             성산1동      532    406.0
245         11160590             화곡4동      519    508.0
268         11170690              수궁동      517    333.0
354         11220670             양재2동      513    485.0
322         11210620              인헌동      512    352.0
106         11070710             면목본동      510    440.0
335         11210810              난곡동      507    363.0
154         11100640             도봉1동      501    443.0
417         11250730             천호2동      498    436.0
150         11100600              창2동      492    447.0
418         11250740               길동      492    425.0
142         11100510             쌍문1동      491    389.0
132         11090630             수유1동      491    415.0
210         11140680              합정동      488    350.0
243         11160570             화곡2동      487    481.0
147         11100560             방학2동      483    414.0
211         11140690             망원1동      481    338.0
137         11090710              송중동      481    269.0
130         11090610              번2동      478    314.0
303         11200530             상도1동      475    371.0
43          11030710              청파동      470    419.0
121         11080760             장위1동      469    378.0
353         11220660             양재1동      467    283.0
224         11150540              목4동      451    388.0
410         11250610             천호1동      444    384.0
352         11220650             방배4동      443    388.0
114         11080630             정릉2동      440    337.0
340         11220530             서초3동      437    298.0
223         11150530              목3동      435    380.0
209         11140660              서교동      435    354.0
358         11230520             논현1동      431    365.0
266         11170650             개봉3동      430    354.0
136         11090700              미아동      424    320.0
332         11210780              은천동      423    278.0
246         11160610             화곡6동      421    400.0
337         11210830              미성동      415    277.0
181         11120590             응암1동      415    372.0
46          11030740              한남동      415    353.0
71          11050600             구의1동      413    362.0
394         11240670             가락2동      411    380.0
271         11170720             개봉1동      403    264.0
414         11250670             성내3동      400    372.0
265         11170640             개봉2동      392    354.0
307         11200630             사당1동      388    340.0
135         11090690              삼양동      387    338.0
174         11110790             공릉1동      384    268.0
324         11210640              서원동      383    212.0
76          11050650             자양2동      380    338.0
219         11140770              공덕동      377    145.0
134         11090650             수유3동      377    343.0
277         11180540             독산3동      375    341.0
101         11070640              묵1동      374    327.0
363         11230630             대치4동      372    339.0
31          11030510              후암동      370    352.0
395         11240680             문정1동      369    301.0
3           11010560              평창동      366    265.0
75          11050640             자양1동      364    322.0
67          11050560             중곡2동      361    341.0
212         11140700             망원2동      361    231.0
213         11140710              연남동      359    307.0
88          11060870             장안1동      359    198.0
27          11020700              다산동      358    308.0
133         11090640             수유2동      357    317.0
128         11080850              석관동      356    305.0
225         11150570             신월1동      355    266.0
317         11210520             보라매동      355    272.0
349         11220620             방배1동      352    300.0
369         11230710             개포4동      348    322.0
138         11090720              송천동      347    301.0
279         11180570             시흥1동      347    314.0
282         11180600             시흥4동      345    296.0
255         11160740             우장산동      344    324.0
359         11230530             논현2동      343    273.0
116         11080650             정릉4동      338    240.0
16          11010730              혜화동      334    256.0
311         11200680              대방동      332    292.0
383         11240560             마천2동      331    210.0
240         11160530             등촌2동      329    321.0
392         11240650             가락본동      328    297.0
15          11010720            청운효자동      326    305.0
184         11120660             신사2동      325    264.0
276         11180530             독산2동      325    296.0
251         11160690              공항동      320    292.0
347         11220600             반포4동      319    235.0
143         11100520             쌍문2동      316    287.0
412         11250650             성내1동      316    272.0
252         11160700             방화1동      313    268.0
272         11170730             오류2동      308    114.0
323         11210630              남현동      308    245.0
382         11240550             마천1동      306    190.0
100         11070620             중화2동      304    244.0
413         11250660             성내2동      304    253.0
361         11230590             삼성2동      303    266.0
350         11220630             방배2동      302    219.0
108         11070730             망우본동      298    214.0
215         11140730             성산2동      298    168.0
334         11210800              청룡동      294    147.0
226         11150580             신월2동      293    180.0
32          11030520            용산2가동      291    204.0
402         11240810              장지동      290    203.0
124         11080810              성북동      290    223.0
93          11070520             면목2동      289    208.0
146         11100550             방학1동      289    240.0
309         11200660             사당4동      288    244.0
127         11080840              종암동      286    224.0
192         11130620             홍제1동      280    177.0
229         11150610             신월5동      279    211.0
198         11130700            남가좌2동      277    201.0
250         11160670             발산1동      276    258.0
384         11240570             방이1동      275    234.0
244         11160580             화곡3동      271    267.0
415         11250710             둔촌2동      269    216.0
281         11180590             시흥3동      269    161.0
261         11170550             구로4동      268    245.0
89          11060880             장안2동      267    146.0
99          11070610             중화1동      266    204.0
156         11110510             월계1동      264    144.0
73          11050620             구의3동      259    229.0
283         11180610             시흥5동      259    211.0
98          11070600             상봉2동      258    235.0
319         11210570              행운동      257    179.0
144         11100530             쌍문3동      256    220.0
348         11220610             방배본동      255    214.0
253         11160710             방화2동      254    229.0
84          11060820              제기동      253    197.0
264         11170620             고척2동      251    163.0
107         11070720           면목3·8동      250    193.0
344         11220570             반포1동      250    195.0
218         11140760              서강동      249    146.0
66          11050550             중곡1동      248    220.0
68          11050570             중곡3동      248    224.0
278         11180550             독산4동      245    224.0
365         11230650             역삼2동      244    205.0
115         11080640             정릉3동      244    155.0
201         11130730              충현동      244    197.0
228         11150600             신월4동      242    169.0
167         11110690             상계5동      242    153.0
308         11200650             사당3동      239    165.0
270         11170710             구로2동      238    192.0
103         11070680             망우3동      236    215.0
102         11070650              묵2동      236    186.0
5           11010580              교남동      235    187.0
227         11150590             신월3동      232    127.0
326         11210660              서림동      232    155.0
260         11170540             구로3동      231    184.0
371         11230730             일원1동      231    160.0
185         11120670              증산동      230    173.0
122         11080770             장위2동      227    181.0
165         11110650             상계1동      227    156.0
375         11230780              청담동      223    157.0
9           11010640              이화동      222    203.0
298         11190730            영등포본동      222    170.0
65          11050540              군자동      220    195.0
97          11070590             상봉1동      218    165.0
62          11040720          금호2·3가동      218    186.0
151         11100610              창3동      217    163.0
297         11190720             대림3동      217    159.0
333         11210790              성현동      216    101.0
2           11010550              부암동      216    132.0
83          11060810              용신동      216    161.0
267         11170670             오류1동      214    162.0
275         11180520             독산1동      213    133.0
193         11130640             홍제3동      212    119.0
203         11130750              신촌동      212    166.0
171         11110760           상계3·4동      209    142.0
327         11210680              신사동      209    185.0
96          11070570             면목7동      206    170.0
304         11200540             상도2동      205    135.0
85          11060830             전농1동      204    177.0
129         11090600              번1동      204    180.0
234         11150660             신정3동      203    129.0
52          11040580              응봉동      202    185.0
325         11210650              신원동      201    116.0
314         11200710              흑석동      200    113.0
338         11220510             서초1동      198    125.0
389         11240620             송파2동      196    143.0
11          11010680             창신2동      194    181.0
360         11230580             삼성1동      192     90.0
153         11100630              창5동      190    148.0
41          11030690             서빙고동      189    121.0
269         11170700             가리봉동      188    131.0
94          11070540             면목4동      188    140.0
274         11180510              가산동      185    121.0
411         11250630             천호3동      183    162.0
35          11030580              효창동      183    158.0
376         11230790             대치2동      181     78.0
313         11200700            신대방2동      180    153.0
288         11190620             양평2동      179    138.0
125         11080820              삼선동      175    141.0
81          11060730             휘경2동      175    134.0
78          11050670             자양4동      175    132.0
420         11250760              상일동      174     62.0
40          11030660            이태원2동      171    151.0
330         11210720              조원동      170    141.0
64          11050530              화양동      168    154.0
380         11240530             거여1동      167    118.0
182         11120600             응암2동      167    123.0
316         11200730             사당2동      166    135.0
95          11070550             면목5동      165    127.0
36          11030590              용문동      163    158.0
195         11130660             홍은1동      163    108.0
159         11110560             공릉2동      162     85.0
104         11070690             신내1동      162     88.0
126         11080830              동선동      162    131.0
70          11050590               능동      162    149.0
320         11210580             낙성대동      162     99.0
208         11140630              신수동      160    128.0
379         11240520             풍납2동      160    111.0
187         11120710              진관동      159     11.0
321         11210610              중앙동      158    124.0
351         11220640             방배3동      153     81.0
14          11010710             숭인2동      152    145.0
310         11200670             사당5동      149    113.0
20          11020580              장충동      149    144.0
162         11110600             중계본동      149     91.0
239         11160520             등촌1동      148    127.0
77          11050660             자양3동      147     73.0
238         11160510              염창동      146    124.0
42          11030700              보광동      145    125.0
374         11230770             압구정동      144     44.0
53          11040590            금호1가동      144    125.0
166         11110660             상계2동      143     91.0
300         11190750              도림동      142    103.0
263         11170610             고척1동      140     77.0
199         11130710            북가좌1동      138     76.0
289         11190630             신길1동      136    106.0
44          11030720            원효로1동      135    124.0
315         11200720            노량진1동      135     70.0
149         11100590              창1동      135    109.0
28          11020710              약수동      133     74.0
403         11240820              위례동      132      1.0
90          11060890             이문1동      132    105.0
366         11230660             도곡1동      132     96.0
328         11210690              신림동      129    116.0
74          11050630              광장동      128     49.0
207         11140610              염리동      127     97.0
206         11140600              대흥동      126     91.0
119         11080710             월곡1동      126     86.0
329         11210710              난향동      124     50.0
407         11250560             고덕2동      124     54.0
342         11220550              잠원동      124     71.0
112         11080610              보문동      123     92.0
139         11090730             삼각산동      120      2.0
404         11250530             명일1동      119    104.0
6           11010600              가회동      116    110.0
336         11210820              삼성동      116     55.0
34          11030570            원효로2동      112     98.0
286         11190560             당산2동      111     76.0
312         11200690            신대방1동      110     87.0
120         11080720             월곡2동      110     75.0
296         11190710             대림2동      109     95.0
356         11230510              신사동      108     62.0
370         11230720             일원본동      106     95.0
49          11040550              사근동      106     91.0
205         11140590              용강동      105     80.0
111         11080600              안암동      103     85.0
257         11160761             방화3동      101    100.0
148         11100570             방학3동      101     56.0
373         11230760              세곡동       99     13.0
160         11110580             하계1동       99     63.0
230         11150620             신월6동       98     39.0
331         11210730              대학동       98     49.0
55          11040650           성수1가1동       96     69.0
57          11040670           성수2가1동       96     56.0
381         11240540             거여2동       95     76.0
155         11100650             도봉2동       94     57.0
123         11080780             장위3동       93     27.0
48          11040540              마장동       92     70.0
262         11170560             구로5동       92     60.0
378         11240510             풍납1동       92     72.0
299         11190740             영등포동       92     67.0
295         11190700             대림1동       90     59.0
113         11080620             정릉1동       89     61.0
82          11060800             청량리동       89     63.0
406         11250550             고덕1동       89     36.0
291         11190660             신길4동       88     28.0
285         11190550             당산1동       88     64.0
145         11100540             쌍문4동       87     61.0
362         11230600             대치1동       86     11.0
87          11060860            답십리2동       86     56.0
202         11130740             북아현동       86     35.0
293         11190680             신길6동       85     56.0
339         11220520             서초2동       84     55.0
39          11030650            이태원1동       84     76.0
273         11170740               항동       83     19.0
216         11140740              상암동       81     34.0
194         11130650             홍제2동       81     50.0
408         11250580             암사2동       81     70.0
256         11160751             가양1동       80     65.0
25          11020680              중림동       80     25.0
186         11120680              수색동       79     49.0
377         11230800             개포2동       78     35.0
346         11220590             반포3동       76     27.0
92          11060910            답십리1동       75     50.0
0           11010530              사직동       74     59.0
217         11140750              도화동       72     52.0
367         11230670             도곡2동       71     28.0
80          11060720             휘경1동       70     44.0
302         11200520            노량진2동       69     50.0
409         11250590             암사3동       69     48.0
191         11130520              천연동       69     48.0
110         11080590             돈암2동       68     38.0
58          11040680           성수2가3동       67     46.0
33          11030530              남영동       67     60.0
292         11190670             신길5동       66     50.0
131         11090620              번3동       66     26.0
341         11220540             서초4동       64      6.0
280         11180580             시흥2동       62     21.0
91          11060900             이문2동       62     26.0
38          11030640             이촌2동       62     12.0
45          11030730             한강로동       61     40.0
79          11060710              회기동       61     57.0
157         11110520             월계2동       61     17.0
59          11040690              송정동       61     58.0
63          11040730              옥수동       61     24.0
56          11040660           성수1가2동       59     34.0
23          11020650             신당5동       57     32.0
54          11040620            금호4가동       57     33.0
318         11210540              청림동       57     19.0
290         11190650             신길3동       57     45.0
118         11080680             길음2동       56     17.0
50          11040560             행당1동       56     40.0

In [100]:
# 노후도 5개 미만
print('=== 노후도 5개 미만 ===')
print(dong_count_final[dong_count_final['노후도_건물수'] < 5][
    ['hdong_code_right', 'hdong_name_right', '노후도_건물수']].to_string())

# 집적도 5개 미만 (NaN 포함)
print('\n=== 집적도 5개 미만 (NaN 포함) ===')
print(dong_count_final[
    dong_count_final['집적도_건물수'].isna() | 
    (dong_count_final['집적도_건물수'] < 5)
][['hdong_code_right', 'hdong_name_right', '노후도_건물수', '집적도_건물수']].to_string())

=== 노후도 5개 미만 ===
    hdong_code_right hdong_name_right  노후도_건물수
169         11110730             상계9동        4
400         11240790             잠실2동        3
399         11240770             잠실6동        3
168         11110720             상계8동        3
249         11160660             가양3동        2
22          11020600             을지로동        2
343         11220560             반포본동        1
396         11240690             문정2동        1
386         11240590              오륜동        1

=== 집적도 5개 미만 (NaN 포함) ===
    hdong_code_right hdong_name_right  노후도_건물수  집적도_건물수
403         11240820              위례동      132      1.0
139         11090730             삼각산동      120      2.0
152         11100620              창4동       53      4.0
393         11240660             가락1동       52      NaN
419         11250750              강일동       47      1.0
357         11230511             개포3동       33      1.0
163         11110610             중계1동       24      NaN
345         11220580             반포2동       20      NaN
37          11030630             이촌1동       19      2.0
158         11110530             월계3동       18      2.0
161         11110590             하계2동       17      NaN
173         11110780           중계2·3동       16      NaN
172         11110770           상계6·7동       13      NaN
170         11110740            상계10동       13      1.0
259         11170520             구로1동        8      1.0
401         11240800             잠실3동        7      NaN
398         11240750             잠실4동        7      NaN
7           11010610      종로1·2·3·4가동        6      3.0
236         11150710              목5동        5      4.0
284         11190540              여의동        5      4.0
169         11110730             상계9동        4      NaN
400         11240790             잠실2동        3      NaN
399         11240770             잠실6동        3      3.0
168         11110720             상계8동        3      NaN
249         11160660             가양3동        2      2.0
22          11020600             을지로동        2      1.0
343         11220560             반포본동        1      NaN
396         11240690             문정2동        1      NaN
386         11240590              오륜동        1      NaN

In [93]:
print('gdf_joined 행정동 수:', gdf_joined['hdong_code_right'].nunique())
print('df_final 행정동 수:', df_final['hdong_code'].nunique())

# 차이나는 동 확인
shp_dongs = set(gdf_joined['hdong_code_right'].dropna().unique())
final_dongs = set(df_final['hdong_code'].dropna().unique())

print('\ngdf_joined에만:', shp_dongs - final_dongs)
print('df_final에만:', final_dongs - shp_dongs)

gdf_joined 행정동 수: 421
df_final 행정동 수: 421

gdf_joined에만: set()
df_final에만: set()

In [104]:
# B068 누락 38개
b068_missing = {
    '가락1동', '가양2동', '가양3동', '강일동', '개포3동', '둔촌1동', '명동',
    '목5동', '문정2동', '반포2동', '반포3동', '반포본동', '상계10동', '상계6·7동',
    '상계8동', '상계9동', '상일2동', '소공동', '수서동', '신내2동', '신정6동',
    '여의동', '오륜동', '월계3가동', '위례동', '을지로동', '이촌1동', '잠실2동',
    '잠실3동', '잠실4동', '잠실6동', '잠실7동', '종로1·2·3·4가동', '중계1동',
    '중계2·3동', '진관동', '창4동', '하계2동'
}

# 진짜 없는 4개 제외
truly_missing = {'소공동', '신정6동', '잠실7동', '둔촌1동'}
b068_missing_real = b068_missing - truly_missing  # 34개

# 건축물대장 노후도 계산 불가
bldg_old_fail = {
    '상계9동', '잠실2동', '잠실6동', '상계8동', '가양3동', '을지로동',
    '반포본동', '문정2동', '오륜동'
}

# 건축물대장 집적도 계산 불가
bldg_density_fail = {
    '위례동', '삼각산동', '창4동', '가락1동', '강일동', '개포3동', '중계1동',
    '반포2동', '이촌1동', '월계3동', '하계2동', '중계2·3동', '상계6·7동',
    '상계10동', '구로1동', '잠실3동', '잠실4동', '종로1·2·3·4가동', '목5동',
    '여의동', '상계9동', '잠실2동', '잠실6동', '상계8동', '가양3동', '을지로동',
    '반포본동', '문정2동', '오륜동'
}

print(f'B068 누락 (진짜 없는 4개 제외): {len(b068_missing_real)}개')

print('\n=== B068 누락 & 노후도도 안 되는 동 ===')
r1 = b068_missing_real & bldg_old_fail
print(f'{len(r1)}개: {sorted(r1)}')

print('\n=== B068 누락 & 집적도도 안 되는 동 ===')
r2 = b068_missing_real & bldg_density_fail
print(f'{len(r2)}개: {sorted(r2)}')

print('\n=== B068 누락이지만 건축물대장으로 노후도+집적도 둘 다 가능한 동 ===')
both_ok = b068_missing_real - bldg_old_fail - bldg_density_fail
print(f'{len(both_ok)}개: {sorted(both_ok)}')

B068 누락 (진짜 없는 4개 제외): 34개

=== B068 누락 & 노후도도 안 되는 동 ===
9개: ['가양3동', '문정2동', '반포본동', '상계8동', '상계9동', '오륜동', '을지로동', '잠실2동', '잠실6동']

=== B068 누락 & 집적도도 안 되는 동 ===
26개: ['가락1동', '가양3동', '강일동', '개포3동', '목5동', '문정2동', '반포2동', '반포본동', '상계10동', '상계6·7동', '상계8동', '상계9동', '여의동', '오륜동', '위례동', '을지로동', '이촌1동', '잠실2동', '잠실3동', '잠실4동', '잠실6동', '종로1·2·3·4가동', '중계1동', '중계2·3동', '창4동', '하계2동']

=== B068 누락이지만 건축물대장으로 노후도+집적도 둘 다 가능한 동 ===
8개: ['가양2동', '명동', '반포3동', '상일2동', '수서동', '신내2동', '월계3가동', '진관동']

In [108]:
dong_count_final[dong_count_final['hdong_name_right'] == '진관동']

    hdong_code_right hdong_name_right  노후도_건물수 hdong_code hdong_name  집적도_건물수
187         11120710              진관동      159   11120710        진관동     11.0